export const WEEKLY_ENGINE_VERSION = "0.1.0";
export const WEEKLY_ENGINE_ENABLED_ENV = "WEEKLY_ENABLED" as const;
export { isWeeklyEnabled, isWeeklyContextualSlidesEnabled, isWeeklyProgressivePublicationEnabled, isWeeklyProgressiveShadowModeEnabled, isWeeklyProgressiveRollbackEnabled } from "./featureFlag";
export { fetchWeeklyForecasts, WEEKLY_FORECAST_DAYS, WEEKLY_FORECAST_TIMEOUT_MS } from "./forecast";
export type { WeeklyForecastBatch } from "./forecast";
export { buildWeeklyProfiles, WEEKLY_PROFILE_VERSION } from "./profiles";
export type { WeeklyDayProfile, WeeklyFullDayProfile, WeeklyProfileSet } from "./profiles";
export { buildWeeklyFixedFacts, WEEKLY_FIXED_FACTS_VERSION, WEEKLY_MORNING_END_HOUR, WEEKLY_MORNING_START_HOUR } from "./fixedFacts";
export type { WeeklyDaylightEndpoint, WeeklyFixedFacts, WeeklyTemperatureFact, WeeklyTemperatureReference } from "./fixedFacts";
export { detectWeeklyEvents } from "./events";
export type { WeeklyEvent, WeeklyEventEvidenceValue, WeeklyEventType } from "./events";
export { consolidateWeeklyEvents } from "./consolidation";
export type { WeeklyStoryEpisode, WeeklyStoryFamily, WeeklyStoryDirection } from "./consolidation";
export { selectWeeklyEvents, selectWeeklyEventsFromProfiles } from "./selection";
export type { SelectedWeeklyEvent, WeeklySelection, WeeklySelectionConfidence, WeeklySelectionRejection, WeeklySelectionRejectionReason, WeeklySelectionStatus } from "./selection";
export { orderWeeklyEvents } from "./narrativeOrder";
export { buildWeeklyConclusion } from "./conclusion";
export type { WeeklyConclusion } from "./conclusion";
export { translateWeeklyActivities } from "./activities";
export type { WeeklyActivity, WeeklyActivityInsight, WeeklyActivityReasonCode, WeeklyActivitySet, WeeklyActivityStatus, WeeklyActivityWindow } from "./activities";
export { buildWeeklyEditorial } from "./editorial";
export { WEEKLY_DAILY_CARD_HOURS } from "./editorial";
export type { WeeklyActivityText, WeeklyDailyCardDetail, WeeklyDailyCardHour, WeeklyDailyCardSlot, WeeklyDailyHighlight, WeeklyDailyHighlightKind, WeeklyDailySummary, WeeklyEditorial, WeeklyEditorialEvent, WeeklySceneReference, WeeklySlide1Content, WeeklySlide1DaylightEndpoint, WeeklySlide1TemperatureFact } from "./editorial";
export { buildWeeklySlide1Synthesis, weeklyThermalClass, WEEKLY_THERMAL_VOCABULARY } from "./synthesis";
export type { WeeklySlide1Synthesis, WeeklySynthesisEvidence, WeeklyThermalClass } from "./synthesis";
export type { WeeklyNumber, WeeklyNumberKind } from "./weeklyNumber";
export { validateWeeklyEditorialSignal, WEEKLY_EDITORIAL_SIGNAL_VERSION } from "./editorialSignals";
export type { WeeklyEditorialEvidence, WeeklyEditorialEvidenceKind, WeeklyEditorialEvidenceSource, WeeklyEditorialMetric, WeeklyEditorialSignal, WeeklyEditorialSignalConfidence, WeeklyEditorialSignalFamily, WeeklyEditorialSignalMode, WeeklyEditorialSignalRole, WeeklyEditorialSignalValidation, WeeklySignalMeasurement, WeeklySignalWindow, WeeklySignalWindowBasis } from "./editorialSignals";
export { buildConsecutiveSeriesReference, buildDatedTemperatureReference, buildHourlyClimateReference, buildRollingRainfallReference, buildSeasonalThresholdReference, dailyCoverage, distribution, normalizeDailyArchiveRow, normalizeHourlyArchiveRow, parseSemicolonArchive, percentile, WEEKLY_CLIMATE_CALENDAR_RADIUS_DAYS, WEEKLY_CLIMATE_MIN_COVERAGE, WEEKLY_CLIMATE_MIN_HOURLY_YEARS, WEEKLY_CLIMATE_REFERENCE_VERSION, WEEKLY_CLIMATE_STATION_ID, WEEKLY_CLIMATE_STATION_NAME, WEEKLY_DAILY_REFERENCE_END_YEAR, WEEKLY_DAILY_REFERENCE_START_YEAR, WEEKLY_HOURLY_REFERENCE_END_YEAR, WEEKLY_HOURLY_REFERENCE_START_YEAR } from "./climateReferences";
export type { ClimateCoverageReport, ClimateDailyMetric, ClimateDailyObservation, ClimateDistribution, ClimateHourlyMetric, ClimateHourlyObservation, ClimateProvenance, ConsecutiveSeriesReference, DatedClimateReference, HourlyClimateReference, RainfallReference, SeasonalThresholdReference } from "./climateReferences";
export { detectClimateDeparture, detectHistoricalExtreme, detectImpactPhenomena, detectIntradayChanges, detectProjectedSeries, detectRecentExtreme, detectRegimeChanges, detectSeasonalFirst, detectWeeklyRainfallDeparture, detectWeeklySignalCandidates, INTRADAY_THRESHOLDS, PHENOMENON_THRESHOLDS, RECENT_EXTREME_THRESHOLDS, REGIME_THRESHOLDS, WEEKLY_SIGNAL_DETECTOR_VERSION } from "./signalDetectors";
export type { ForecastDailyFact, ProjectedSeriesInput, SeasonalFirstInput, WeeklySignalCandidate, WeeklySignalDetectorKind } from "./signalDetectors";
export { activateWeeklyEditorialSignals, WEEKLY_EDITORIAL_ACTIVATION_VERSION } from "./editorialActivation";
export type { WeeklyEditorialActivationResult } from "./editorialActivation";
export { rankAndDeduplicateWeeklySignals, scoreWeeklySignalCandidate, WEEKLY_SIGNAL_MIN_TOTAL_SCORE, WEEKLY_SIGNAL_RANKING_VERSION } from "./signalRanking";
export type { RankedWeeklySignalCandidate, WeeklySignalRankingResult, WeeklySignalRejectionReason, WeeklySignalScoreDimension, WeeklySignalScores } from "./signalRanking";
export { buildWeeklySignalCopies, buildWeeklySignalCopy, WEEKLY_SIGNAL_COPY_VERSION } from "./signalCopy";
export type { WeeklySignalClaimStatus, WeeklySignalCopy } from "./signalCopy";
export { buildWeeklyComplementaryPresentation, buildWeeklyComplementarySlides, WEEKLY_COMPLEMENTARY_SLIDES_VERSION } from "./complementarySlides";
export type { WeeklyComplementaryComparisonItem, WeeklyComplementaryLayout, WeeklyComplementaryPresentation, WeeklyComplementarySlide, WeeklyComplementarySlidePlan, WeeklyComplementarySlideRole, WeeklyComplementaryTheme, WeeklyComplementaryVisual } from "./complementarySlides";
export { buildWeeklyContextualPipeline, buildWeeklyContextualSelection, WEEKLY_CONTEXTUAL_PIPELINE_VERSION } from "./contextualPipeline";
export type { WeeklyContextualInput, WeeklyContextualPipelineResult } from "./contextualPipeline";
export { assertWeeklyComplementaryPreflight, preflightWeeklyComplementarySlides, weeklyComplementaryPlanFingerprint, WEEKLY_COMPLEMENTARY_PREFLIGHT_VERSION } from "./complementaryPreflight";
export type { WeeklyComplementaryPreflight, WeeklyComplementaryPreflightCheck, WeeklyComplementaryPreflightCheckId, WeeklyComplementaryPreflightContext } from "./complementaryPreflight";
export { buildWeeklyCarouselPlan, renderWeeklyCarousel, WEEKLY_CAROUSEL_HEIGHT, WEEKLY_CAROUSEL_MAX_EVENT_SLIDES, WEEKLY_CAROUSEL_VERSION, WEEKLY_CAROUSEL_WIDTH, WEEKLY_COMPLEMENTARY_DAILY_FEED_GRID, WEEKLY_EDITORIAL_MASTER_GRID, WEEKLY_OVERVIEW_MASTER_URL, WEEKLY_SLIDE1_DAILY_FEED_GRID, WEEKLY_SLIDE2_DAILY_FEED_GRID, WEEKLY_STORY_HEIGHT, WEEKLY_STORY_WIDTH } from "./carousel";
export type { WeeklyCarouselBuildOptions, WeeklyCarouselRenderOptions, WeeklyCarouselDailyCardDetail, WeeklyCarouselDailyCardSlot, WeeklyCarouselDailySummary, WeeklyCarouselSlide1Content, WeeklyDailyPictogramReference, WeeklyCarouselPlan, WeeklyCarouselSlide, WeeklyCarouselSlideKind, WeeklyStoryRelay } from "./carousel";
export { localDateIsMonday, nextMondayOrSame, weeklyRangeForDate } from "./schedule";
export type { WeeklyDateRange } from "./schedule";
export { validateWeeklyActivation } from "./activation";
export type { WeeklyActivationCheck, WeeklyActivationValidation } from "./activation";
export { summarizeWeeklyEditorialPilot, validateWeeklyEditorialPilot, WEEKLY_EDITORIAL_PILOT_VERSION } from "./pilotValidation";
export type { WeeklyEditorialPilotBatch, WeeklyEditorialPilotCheck, WeeklyEditorialPilotInput, WeeklyEditorialPilotReport, WeeklyEditorialPilotSource, WeeklyEditorialPilotStatus } from "./pilotValidation";
export { evaluateWeeklyProgressivePublication, resolveWeeklyPublicSurface, logWeeklyProgressivePublication } from "./progressivePublication";
export type { WeeklyProgressivePublicationCheck, WeeklyProgressivePublicationDecision, WeeklyProgressivePublicationMode, WeeklyPublicSurface } from "./progressivePublication";
