export const WEEKLY_ENGINE_VERSION = "0.1.0";
export const WEEKLY_ENGINE_ENABLED_ENV = "WEEKLY_ENABLED" as const;
export { isWeeklyEnabled } from "./featureFlag";
export { fetchWeeklyForecasts, WEEKLY_FORECAST_DAYS } from "./forecast";
export type { WeeklyForecastBatch } from "./forecast";
export { buildWeeklyProfiles, WEEKLY_PROFILE_VERSION } from "./profiles";
export type { WeeklyDayProfile, WeeklyFullDayProfile, WeeklyProfileSet } from "./profiles";
export { detectWeeklyEvents } from "./events";
export type { WeeklyEvent, WeeklyEventEvidenceValue, WeeklyEventType } from "./events";
export { selectWeeklyEvents, selectWeeklyEventsFromProfiles } from "./selection";
export type { SelectedWeeklyEvent, WeeklySelection, WeeklySelectionConfidence, WeeklySelectionStatus } from "./selection";
export { translateWeeklyActivities } from "./activities";
export type { WeeklyActivity, WeeklyActivityInsight, WeeklyActivityReasonCode, WeeklyActivitySet, WeeklyActivityStatus, WeeklyActivityWindow } from "./activities";
export { buildWeeklyEditorial } from "./editorial";
export type { WeeklyActivityText, WeeklyEditorial, WeeklyEditorialEvent, WeeklySceneReference } from "./editorial";
export { buildWeeklyCarouselPlan, renderWeeklyCarousel, WEEKLY_CAROUSEL_HEIGHT, WEEKLY_CAROUSEL_VERSION, WEEKLY_CAROUSEL_WIDTH, WEEKLY_STORY_HEIGHT, WEEKLY_STORY_WIDTH } from "./carousel";
export type { WeeklyCarouselPlan, WeeklyCarouselSlide, WeeklyCarouselSlideKind, WeeklyStoryRelay } from "./carousel";
export { localDateIsMonday, nextMondayOrSame, weeklyRangeForDate } from "./schedule";
export type { WeeklyDateRange } from "./schedule";
export { validateWeeklyActivation } from "./activation";
export type { WeeklyActivationCheck, WeeklyActivationValidation } from "./activation";
