export const WEEKLY_ENGINE_VERSION = "0.1.0";
export const WEEKLY_ENGINE_ENABLED_ENV = "WEEKLY_ENABLED" as const;
export { isWeeklyEnabled } from "./featureFlag";
export { fetchWeeklyForecasts, WEEKLY_FORECAST_DAYS, WEEKLY_FORECAST_TIMEOUT_MS } from "./forecast";
export type { WeeklyForecastBatch } from "./forecast";
export { buildWeeklyProfiles, WEEKLY_PROFILE_VERSION } from "./profiles";
export type { WeeklyDayProfile, WeeklyFullDayProfile, WeeklyProfileSet } from "./profiles";
export { buildWeeklyFixedFacts, WEEKLY_FIXED_FACTS_VERSION, WEEKLY_MORNING_END_HOUR, WEEKLY_MORNING_START_HOUR } from "./fixedFacts";
export type { WeeklyDaylightEndpoint, WeeklyFixedFacts, WeeklyTemperatureFact, WeeklyTemperatureReference } from "./fixedFacts";
export { detectWeeklyEvents } from "./events";
export type { WeeklyEvent, WeeklyEventEvidenceValue, WeeklyEventType } from "./events";
export { consolidateWeeklyEvents } from "./consolidation";
export type { WeeklyStoryEpisode, WeeklyStoryFamily, WeeklyStoryDirection } from "./consolidation";
export { selectWeeklyEvents, selectWeeklyEventsFromProfiles } from "./selection";
export type { SelectedWeeklyEvent, WeeklySelection, WeeklySelectionConfidence, WeeklySelectionRejection, WeeklySelectionRejectionReason, WeeklySelectionStatus } from "./selection";
export { orderWeeklyEvents } from "./narrativeOrder";
export { buildWeeklyConclusion } from "./conclusion";
export type { WeeklyConclusion } from "./conclusion";
export { translateWeeklyActivities } from "./activities";
export type { WeeklyActivity, WeeklyActivityInsight, WeeklyActivityReasonCode, WeeklyActivitySet, WeeklyActivityStatus, WeeklyActivityWindow } from "./activities";
export { buildWeeklyEditorial } from "./editorial";
export { WEEKLY_DAILY_CARD_HOURS } from "./editorial";
export type { WeeklyActivityText, WeeklyDailyCardDetail, WeeklyDailyCardHour, WeeklyDailyCardSlot, WeeklyDailyHighlight, WeeklyDailyHighlightKind, WeeklyDailySummary, WeeklyEditorial, WeeklyEditorialEvent, WeeklySceneReference, WeeklySlide1Content, WeeklySlide1DaylightEndpoint, WeeklySlide1TemperatureFact } from "./editorial";
export { buildWeeklySlide1Synthesis, weeklyThermalClass, WEEKLY_THERMAL_VOCABULARY } from "./synthesis";
export type { WeeklySlide1Synthesis, WeeklySynthesisEvidence, WeeklyThermalClass } from "./synthesis";
export type { WeeklyNumber, WeeklyNumberKind } from "./weeklyNumber";
export { validateWeeklyEditorialSignal, WEEKLY_EDITORIAL_SIGNAL_VERSION } from "./editorialSignals";
export type { WeeklyEditorialEvidence, WeeklyEditorialEvidenceKind, WeeklyEditorialEvidenceSource, WeeklyEditorialMetric, WeeklyEditorialSignal, WeeklyEditorialSignalConfidence, WeeklyEditorialSignalFamily, WeeklyEditorialSignalMode, WeeklyEditorialSignalRole, WeeklyEditorialSignalValidation, WeeklySignalMeasurement, WeeklySignalWindow, WeeklySignalWindowBasis } from "./editorialSignals";
export { buildWeeklyCarouselPlan, renderWeeklyCarousel, WEEKLY_CAROUSEL_HEIGHT, WEEKLY_CAROUSEL_MAX_EVENT_SLIDES, WEEKLY_CAROUSEL_VERSION, WEEKLY_CAROUSEL_WIDTH, WEEKLY_OVERVIEW_MASTER_URL, WEEKLY_SLIDE1_DAILY_FEED_GRID, WEEKLY_SLIDE2_DAILY_FEED_GRID, WEEKLY_STORY_HEIGHT, WEEKLY_STORY_WIDTH } from "./carousel";
export type { WeeklyCarouselDailyCardDetail, WeeklyCarouselDailyCardSlot, WeeklyCarouselDailySummary, WeeklyCarouselSlide1Content, WeeklyDailyPictogramReference, WeeklyCarouselPlan, WeeklyCarouselSlide, WeeklyCarouselSlideKind, WeeklyStoryRelay } from "./carousel";
export { localDateIsMonday, nextMondayOrSame, weeklyRangeForDate } from "./schedule";
export type { WeeklyDateRange } from "./schedule";
export { validateWeeklyActivation } from "./activation";
export type { WeeklyActivationCheck, WeeklyActivationValidation } from "./activation";
