import { CITIES } from "../src/config/cities";
import { buildConsensus } from "../src/engine/consensus";
import { buildCandidateProduct } from "../src/engine/verdict";
import { renderInstagramOfficial24 } from "../src/ui/instagramOfficial24";
import { renderInstagramCarouselV3Preview } from "../src/ui/instagramCarouselV3Preview";
import { enhanceInstagramWithV3OfficialStudio } from "../src/ui/instagramV3ParallelStudio";
import type { HourPoint, ModelForecast, WeatherFamily } from "../src/types";

const date="2026-08-27";
const specs:Array<[string,WeatherFamily,number]>=[["arome","meteofrance",.30],["ecmwf_ifs","ecmwf_physics",.25],["ecmwf_aifs","ecmwf_ai",.15],["icon_eu","dwd",.17],["gfs","noaa",.13]];
function forecast(id:string,family:WeatherFamily,weight:number):ModelForecast{const hourly:HourPoint[]=[];for(let h=0;h<24;h++){const wet=h>=16&&h<=20,cloud=h<13?20:h<16?70:92,temp=17+Math.min(h,16)*.45-(wet?1:0);hourly.push({time:`${date}T${String(h).padStart(2,"0")}:00`,temperatureC:temp,apparentTemperatureC:temp,precipitationMm:wet?.8:0,rainMm:wet?.8:0,cloudCoverPct:cloud,cloudCoverLowPct:cloud,cloudCoverMidPct:cloud,cloudCoverHighPct:cloud,windSpeedKmh:16,windGustKmh:28,weatherCode:wet?61:cloud>=85?3:cloud>=50?2:1});}return{modelId:id,family,weight,fetchedAt:new Date().toISOString(),latitude:43.54,longitude:-1.46,hourly};}
const forecasts=specs.map(([a,b,c])=>forecast(a,b,c));
const payload=buildCandidateProduct(CITIES.tarnos,date,buildConsensus(forecasts),forecasts,{},"TEST_7I");
let checks=0;const ok=(value:boolean,label:string)=>{if(!value)throw new Error(`FAIL:${label}`);checks++;};
const official=renderInstagramOfficial24(payload,CITIES.tarnos);
const enhanced=enhanceInstagramWithV3OfficialStudio(official);
ok(enhanced.includes('id="v3OfficialStudio"'),'official_section');
ok(enhanced.includes('/instagram-v3-preview?embed=1&studio=official'),'official_iframe');
ok(enhanced.includes('V3 OFFICIEL · MANUEL'),'official_badge');
ok(enhanced.includes('FORMAT OFFICIEL DE PUBLICATION MANUELLE'),'official_heading');
ok(enhanced.includes('L’automatisation Instagram reste encore sur le format V2'),'automation_v2_message');
ok(enhanced.includes('id="v2RollbackPublication"'),'v2_rollback_anchor');
ok(enhanced.includes('PUBLICATION V2 · ROLLBACK'),'v2_rollback_title');
ok(enhanced.includes('id="shareFeed"'),'v2_rollback_export_preserved');
ok(enhanced.includes('id="shareStory"') && enhanced.includes('id="shareLegendStory"'),'stories_preserved');
ok(enhanced.indexOf('id="v3OfficialStudio"') < enhanced.indexOf('STORY / REEL'),'v3_before_stories');
ok(enhanced.indexOf('STORY / REEL') < enhanced.indexOf('PUBLICATION V2 · ROLLBACK'),'stories_before_v2_rollback');
ok(enhanced.includes('<!--LOKA_EDITORIAL_STUDIO_MOUNT-->'),'editorial_marker_preserved');
const embedded=renderInstagramCarouselV3Preview(payload,CITIES.tarnos,{embedded:true,studioOfficial:true});
ok(embedded.includes('V3 · FORMAT OFFICIEL MANUEL'),'official_embedded_badge');
ok(embedded.includes('automatisation reste encore sur le V2'),'official_embedded_automation_note');
ok(embedded.includes('rollback V2 reste disponible'),'official_embedded_rollback_note');
const standalone=renderInstagramCarouselV3Preview(payload,CITIES.tarnos,{studioOfficial:true});
ok(standalone.includes('V3 OFFICIEL · MANUEL'),'official_standalone_badge');
ok(standalone.includes('Format officiel de publication manuelle'),'official_standalone_message');
ok(standalone.includes('automatisation V3 reste désactivée'),'official_export_safety');
console.log(`instagramV3OfficialStudio: ${checks} checks passed`);
