export function renderAdmin(): string {
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LOKA! Admin V2</title><style>
body{margin:0;background:#071b3b;color:#fff;font-family:-apple-system,BlinkMacSystemFont,Arial,sans-serif;padding:22px}.wrap{max-width:620px;margin:auto}h1{color:#fdb515}section{background:rgba(255,255,255,.08);border-radius:20px;padding:18px;margin:14px 0}input,button{width:100%;padding:13px;border-radius:12px;border:0;margin:7px 0;font-size:16px}button{background:#fdb515;color:#071b3b;font-weight:800}pre{white-space:pre-wrap;overflow-wrap:anywhere;color:#dce5f2;font-size:12px}.muted{color:#b8c4d8;font-size:13px}.linkbtn{display:block;width:100%;padding:13px;border-radius:12px;background:#fff;color:#071b3b;text-align:center;text-decoration:none;font-weight:800;margin-top:7px}
</style></head><body><main class="wrap"><h1>LOKA! Admin V2</h1><p class="muted">Les générations manuelles sont des previews techniques. Elles ne modifient jamais la scène officielle sans promotion explicite.</p><section><h2>Token</h2><input id="token" type="password" placeholder="ADMIN_TOKEN"></section><section><h2>Génération manuelle</h2><button id="run">Générer Tarnos</button><pre id="runOut"></pre></section><section><h2>Promouvoir une génération vérifiée</h2><input id="gid" inputmode="numeric" placeholder="ID de génération"><input id="reason" placeholder="Raison technique"><button id="promote">Promouvoir</button><pre id="promoteOut"></pre></section><section><h2>Preview 24 scènes</h2><p class="muted">Accès direct au nouveau mode de visualisation interne, par paquets de 5, avec rendu V24 et données fictives.</p><a class="linkbtn" href="/instagram-scenes-preview?city=tarnos&pack=1&view=story">Ouvrir le preview des scènes</a></section><script>
const auth=()=>({'authorization':'Bearer '+document.getElementById('token').value});
const out=(id,v)=>document.getElementById(id).textContent=JSON.stringify(v,null,2);
document.getElementById('run').onclick=async()=>{try{const r=await fetch('/api/run?city=tarnos',{method:'POST',headers:auth()});out('runOut',await r.json())}catch(e){out('runOut',{error:String(e)})}};
document.getElementById('promote').onclick=async()=>{try{const generationId=Number(document.getElementById('gid').value);const reason=document.getElementById('reason').value;const r=await fetch('/api/admin/scene/promote',{method:'POST',headers:{...auth(),'content-type':'application/json'},body:JSON.stringify({generationId,reason})});out('promoteOut',await r.json())}catch(e){out('promoteOut',{error:String(e)})}};
</script></main></body></html>`;
}
