const STYLE = `<style>
.v3-media-access{background:#fff;border-radius:24px;padding:18px;margin:0 0 18px;box-shadow:0 12px 45px rgba(0,0,0,.06)}.v3-media-access h2{font-size:18px;line-height:1.15;margin:5px 0 6px}.v3-media-access p{font-size:11px;line-height:1.5;color:#73716c;margin:0}.v3-media-access-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v3-media-access-badge{font-size:9px;font-weight:850;letter-spacing:.08em;color:#164e2d;background:#e7f5eb;padding:7px 9px;border-radius:999px;white-space:nowrap}.v3-media-access-state{margin-top:12px;padding:10px 12px;border-radius:14px;background:#f7f6f2;font-size:11px;color:#73716c}.v3-media-access-state.ready{color:#24653a;background:#edf7ef}.v3-media-access-state.error{color:#9c2f2f;background:#fff0f0}.v3-media-access-links{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.v3-media-access-links a,.v3-media-access-generate{border:0;border-radius:14px;padding:13px 10px;text-decoration:none;text-align:center;font:750 13px/1 -apple-system,BlinkMacSystemFont,sans-serif}.v3-media-access-links a{background:#171715;color:#fff}.v3-media-access-links a.disabled{opacity:.34;pointer-events:none}.v3-media-access-generate{width:100%;margin-top:8px;background:#ecebe7;color:#171715;cursor:pointer}.v3-media-access-generate:disabled{opacity:.55;cursor:wait}.v3-media-access-auth{display:none;margin-top:9px}.v3-media-access-auth.visible{display:block}.v3-media-access-auth label{display:block;font-size:10px;font-weight:750;color:#625f58;margin-bottom:5px}.v3-media-access-auth input{width:100%;border:1px solid #dedbd3;border-radius:12px;padding:11px 12px;font-size:15px;background:#fff;color:#171715}.v3-media-access-help{font-size:10px;line-height:1.45;color:#8d8983;margin-top:9px}@media(max-width:420px){.v3-media-access-top{display:block}.v3-media-access-badge{display:inline-block;margin:0 0 8px}.v3-media-access-links{grid-template-columns:1fr}}
</style>`;

const MARKUP = `<section class="v3-media-access" id="v3MediaAccessStandalone"><div class="v3-media-access-top"><div><p>ACCÈS SIMPLE</p><h2>Images V3 générées automatiquement</h2><p>Génère puis ouvre directement les deux PNG, sans passer par Cloudflare ni par du JSON.</p></div><span class="v3-media-access-badge">PNG 1080 × 1350</span></div><div class="v3-media-access-state" id="v3MediaAccessState">Vérification des images…</div><div class="v3-media-access-links"><a id="v3MediaAccessPage1" class="disabled" href="#" aria-disabled="true" target="_blank" rel="noopener">Voir PNG Page 1</a><a id="v3MediaAccessPage2" class="disabled" href="#" aria-disabled="true" target="_blank" rel="noopener">Voir PNG Page 2</a></div><button class="v3-media-access-generate" id="v3MediaAccessGenerate" type="button">Générer / actualiser les PNG</button><div class="v3-media-access-auth" id="v3MediaAccessAuth"><label for="v3MediaAccessToken">Mot de passe administrateur</label><input id="v3MediaAccessToken" type="password" autocomplete="current-password" placeholder="ADMIN_TOKEN"></div><div class="v3-media-access-help">Les images temporaires sont générées par le mode Shadow. Aucune publication Instagram n’est déclenchée.</div></section>`;

const SCRIPT = `<script>
(function(){
const root=document.getElementById('v3MediaAccessStandalone');if(!root)return;
const STORAGE_KEY='loka_admin_token_v2',CITY='tarnos';
const state=document.getElementById('v3MediaAccessState'),p1=document.getElementById('v3MediaAccessPage1'),p2=document.getElementById('v3MediaAccessPage2'),generate=document.getElementById('v3MediaAccessGenerate'),auth=document.getElementById('v3MediaAccessAuth'),tokenInput=document.getElementById('v3MediaAccessToken');
function token(){try{return localStorage.getItem(STORAGE_KEY)||'';}catch{return'';}}
function save(v){try{if(v)localStorage.setItem(STORAGE_KEY,v);else localStorage.removeItem(STORAGE_KEY);}catch{}}
function status(msg,kind=''){state.textContent=msg;state.className='v3-media-access-state'+(kind?' '+kind:'');}
function disable(){for(const a of [p1,p2]){a.href='#';a.classList.add('disabled');a.setAttribute('aria-disabled','true');}}
function apply(plan){const r=plan&&plan.render;if(!r||r.status!=='RENDERED'||!Array.isArray(r.assets)){disable();return false;}const a1=r.assets.find(a=>a.position===1&&a.publicUrl),a2=r.assets.find(a=>a.position===2&&a.publicUrl);if(!a1||!a2){disable();return false;}p1.href=a1.publicUrl;p2.href=a2.publicUrl;for(const a of [p1,p2]){a.classList.remove('disabled');a.removeAttribute('aria-disabled');}status('Images prêtes'+(plan.forecastDate?' · '+plan.forecastDate:''),'ready');return true;}
function showAuth(){auth.classList.toggle('visible',!token());}
async function latest(){const t=token();showAuth();if(!t){disable();status('Clique sur « Générer / actualiser les PNG »');return;}try{const res=await fetch('/api/admin/instagram/v3-shadow?city='+encodeURIComponent(CITY)+'&limit=1',{headers:{authorization:'Bearer '+t}});let data={};try{data=await res.json();}catch{}if(res.status===401){save('');showAuth();disable();status('Mot de passe administrateur à saisir','error');return;}if(!res.ok){disable();status('Aucune image disponible pour le moment');return;}const plan=data.audits&&data.audits[0]&&data.audits[0].plan;if(!apply(plan))status('Aucune image générée pour le moment');}catch{disable();status('Vérification impossible pour le moment','error');}}
generate.onclick=async()=>{const t=token()||String(tokenInput.value||'').trim();if(!t){auth.classList.add('visible');status('Entre ton mot de passe puis appuie à nouveau','error');tokenInput.focus();return;}generate.disabled=true;generate.textContent='Génération en cours…';status('Création de Page 1 et Page 2…');try{const res=await fetch('/api/admin/instagram/v3-shadow/run?city='+encodeURIComponent(CITY),{method:'POST',headers:{authorization:'Bearer '+t}});let data={};try{data=await res.json();}catch{}if(res.status===401){save('');showAuth();disable();status('Mot de passe incorrect','error');tokenInput.focus();return;}if(!res.ok||!data.plan){disable();status('Génération impossible : '+String(data.error||('HTTP '+res.status)),'error');return;}save(t);tokenInput.value='';showAuth();if(!apply(data.plan)){status('PNG non générés : '+String(data.plan&&data.plan.render&&data.plan.render.detail||'rendu bloqué'),'error');return;}status('Page 1 et Page 2 sont prêtes','ready');}catch(e){disable();status('Erreur réseau : '+String(e),'error');}finally{generate.disabled=false;generate.textContent='Générer / actualiser les PNG';}};
disable();setTimeout(latest,80);
})();
</script>`;

export function enhanceInstagramWithV3MediaAccess(html: string): string {
  // 7L.1 already contains the same controls inside the official V3 block.
  // In that case keep a single panel. Otherwise inject this standalone panel
  // before the first Story so it is visible regardless of payload.analysis.
  if (html.includes('id="v3AutoMedia"') || html.includes('id="v3MediaAccessStandalone"')) return html;
  const styleMarker = '</style><!--LOKA_EDITORIAL_STYLE_MOUNT-->';
  const storyMarker = '<div class="visual-card"><div class="visual-head"><div class="visual-title">STORY / REEL</div>';
  if (!html.includes(styleMarker)) throw new Error('instagram_v3_media_access_style_marker_missing');
  if (!html.includes(storyMarker)) throw new Error('instagram_v3_media_access_story_marker_missing');
  let result = html.replace(styleMarker, `</style>${STYLE}<!--LOKA_EDITORIAL_STYLE_MOUNT-->`);
  result = result.replace(storyMarker, `${MARKUP}${storyMarker}`);
  result = result.replace('</body>', `${SCRIPT}</body>`);
  return result;
}
