import type { CityConfig, OfficialPublicPayloadV24, HourlyCondition } from "../types";
import { buildEngagementEditorial } from "../engine/editorial24/engagement";
import { scene24DisplayTitle } from "../engine/scenes24/displayTitles";
import {
  PICTOGRAM_LIBRARY_VERSION,
  PICTOGRAM_STYLE,
  hourlyConditionToPictogram,
  solarPictogramDataUrl,
  visualIconToPictogram,
  weatherPictogramDataUrl
} from "./pictogramLibrary";
import { solarPresentation } from "./solarTimes";
import { LOKA_LOGO_DATA_URL } from "./lokaBrand";
import { LOKA_DAILY_FEED_FRAME } from "./feedFrame";
import { LOKA_EDITORIAL_SUMMARY_FRAME } from "./editorialSummaryFrame";
import { LOKA_GRAPHIC_SYSTEM } from "./lokaGraphicSystem";
import type { DailyComparisonStory } from "../engine/dailyComparison";


function safeJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");
}

export function renderInstagramDailyGraphicPreview(
  payload: OfficialPublicPayloadV24,
  city: CityConfig,
  comparison: DailyComparisonStory | null = null
): string {
  if (
    payload.editorial.scene.id !== payload.scene.id ||
    payload.editorial.scene.title !== payload.scene.label ||
    payload.editorial.scene.visualIcon !== payload.scene.visualIcon
  ) {
    throw new Error("instagram_editorial_scene_mismatch");
  }

  const hourly = payload.hourly as Array<{
    hour: number;
    temperatureC: number;
    condition: HourlyCondition;
    precipitationMm: number;
  }>;
  const engagement = payload.editorial.engagement
    ?? buildEngagementEditorial(payload.city, payload.date, payload.editorial.facts);

  const model = {
    city: payload.city,
    date: payload.date,
    timezone: city.timezone,
    masterUrl: payload.scene.masterUrl,
    scene: {
      id: payload.editorial.scene.id,
      title: scene24DisplayTitle(payload.scene.id),
      canonicalTitle: payload.editorial.scene.title,
      pictogramUrl: weatherPictogramDataUrl(visualIconToPictogram(payload.editorial.scene.visualIcon))
    },
    visual: payload.editorial.visual,
    social: payload.editorial.social,
    legendText: [payload.editorial.social.paragraph1, payload.editorial.social.paragraph2].filter(Boolean).join("\n\n"),
    engagement,
    temps: payload.temperatures,
    hourly: hourly.map((item) => ({
      ...item,
      pictogramUrl: weatherPictogramDataUrl(hourlyConditionToPictogram(item.condition))
    })),
    solar: solarPresentation(city, payload.date),
    solarPictograms: {
      dawn: solarPictogramDataUrl("dawn"),
      sunrise: solarPictogramDataUrl("sunrise"),
      noon: solarPictogramDataUrl("noon"),
      sunset: solarPictogramDataUrl("sunset"),
      dusk: solarPictogramDataUrl("dusk")
    },
    brand: {
      logoUrl: LOKA_LOGO_DATA_URL
    },
    pictogramLibrary: {
      version: PICTOGRAM_LIBRARY_VERSION,
      ink: PICTOGRAM_STYLE.ink,
      gold: PICTOGRAM_STYLE.gold
    },
    ...(comparison ? { comparison } : {})
  };

  const comparisonCard = comparison ? `
<div class="visual-card"><div class="visual-head"><div class="visual-title">STORY · COMPARAISON DU JOUR</div><div class="visual-size">1080 × 1920 · 9:16</div></div><div class="canvas-wrap"><canvas id="comparisonStory" width="1080" height="1920"></canvas></div><button class="primary" id="shareComparisonStory">Partager / enregistrer la Story comparative</button><div class="note">Ce visuel n’est généré que si le moteur détecte un signal comparatif suffisamment solide.</div></div>` : `
<div class="toolbar"><div class="visual-title">STORY · COMPARAISON DU JOUR</div><div class="muted" style="margin-top:8px">Aucun signal comparatif ne franchit aujourd’hui les seuils de fiabilité. Aucune Story artificielle n’est générée.</div></div>`;

  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>LOKA! — Variante graphique journalière</title><style>
:root{--ink:#171715;--muted:#73716c;--paper:#ecebe7}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;padding:max(14px,env(safe-area-inset-top)) 12px max(26px,env(safe-area-inset-bottom))}.wrap{width:min(100%,580px);margin:auto}.toolbar{background:#fff;border-radius:24px;padding:18px;margin-bottom:14px}.topline{display:flex;align-items:center;justify-content:space-between;gap:12px}.brand{font-size:12px;font-weight:760;letter-spacing:.16em}.badge{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#8a6100;background:#fff6d8;padding:6px 8px;border-radius:999px}h1{font-size:23px;line-height:1.08;margin:14px 0 5px}.muted{font-size:12px;line-height:1.5;color:var(--muted)}.visual-card{margin:0 0 18px}.visual-head{display:flex;align-items:end;justify-content:space-between;gap:12px;padding:0 4px 9px}.visual-title{font-size:14px;font-weight:760;letter-spacing:.08em}.visual-size{font-size:11px;color:var(--muted)}button{border:0;border-radius:14px;padding:14px 10px;text-align:center;font:650 13px/1 -apple-system,BlinkMacSystemFont,sans-serif;cursor:pointer}.primary{background:#171715;color:#fff;width:100%;margin-top:10px}.secondary{background:#f1f1ee;color:#171715}.canvas-wrap{background:#d8d8d4;border-radius:26px;overflow:hidden;box-shadow:0 18px 70px rgba(0,0,0,.14)}canvas{display:block;width:100%;height:auto}.note{text-align:center;font-size:11px;color:#8d8983;line-height:1.45;padding:2px 12px 14px}.caption-card{background:#fff;border-radius:24px;padding:18px;margin:4px 0 18px}.caption-title{font-size:14px;font-weight:760;letter-spacing:.08em}.caption-help{font-size:11px;line-height:1.4;color:var(--muted);margin-top:4px}.copy-label{font-size:11px;font-weight:760;letter-spacing:.08em;color:#5f5d58;margin:16px 0 7px}.copy-box{margin:0;white-space:pre-wrap;word-break:break-word;background:#f4f3f0;border-radius:16px;padding:14px;font:500 14px/1.55 -apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;color:#171715}.copy-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.copy-actions button{margin:0;width:100%}.copy-all{margin-top:10px}.copy-status{min-height:18px;padding-top:8px;text-align:center;font-size:11px;color:#24653a}@media(max-width:420px){.copy-actions{grid-template-columns:1fr}}
</style><!--LOKA_EDITORIAL_STYLE_MOUNT--></head><body><div class="wrap"><div class="toolbar"><div class="topline"><div class="brand">LOKA!</div><div class="badge">Test graphique · parallèle</div></div><h1>Variante journalière</h1><div class="muted" id="summary">${payload.city} · scène ${String(payload.scene.id).padStart(2,"0")} · mêmes données que la production</div></div>
<div class="visual-card"><div class="visual-head"><div class="visual-title">STORY / REEL</div><div class="visual-size">1080 × 1920 · 9:16</div></div><div class="canvas-wrap"><canvas id="story" width="1080" height="1920"></canvas></div><button class="primary" id="shareStory">Partager / enregistrer la Story</button></div>
<div class="visual-card"><div class="visual-head"><div class="visual-title">STORY · LÉGENDE DU JOUR</div><div class="visual-size">1080 × 1920 · 9:16</div></div><div class="canvas-wrap"><canvas id="legendStory" width="1080" height="1920"></canvas></div><button class="primary" id="shareLegendStory">Partager / enregistrer la Story légende</button><div class="note">La légende est posée directement sur le fond météo, en grand format éditorial. Elle reste identique à celle de la publication et se modifie une seule fois dans l’éditeur.</div></div>
${comparisonCard}
<div class="visual-card"><div class="visual-head"><div class="visual-title">PUBLICATION</div><div class="visual-size">1080 × 1440 · 3:4</div></div><div class="canvas-wrap"><canvas id="feed" width="${LOKA_DAILY_FEED_FRAME.width}" height="${LOKA_DAILY_FEED_FRAME.height}"></canvas></div><button class="primary" id="shareFeed">Partager / enregistrer la Publication</button></div>
<div class="note">Bibliothèque officielle LOKA! Premium · bleu marine, accent or et volume léger. La météo et les textes proviennent exclusivement du moteur V2.</div>
<!--LOKA_EDITORIAL_STUDIO_MOUNT-->
<div class="caption-card"><div class="caption-title">LÉGENDE INSTAGRAM</div><div class="caption-help">Texte officiel produit par Editorial Engine V2.</div><div class="copy-label">LÉGENDE</div><pre class="copy-box" id="captionText"></pre><div class="copy-actions"><button class="secondary" id="copyCaption">Copier la légende</button><button class="secondary" id="copyHashtags">Copier les hashtags</button></div><div class="copy-label">HASHTAGS</div><pre class="copy-box" id="hashtagsText"></pre><button class="primary copy-all" id="copyAll">Tout copier</button><div class="copy-status" id="copyStatus" aria-live="polite"></div></div></div><script>
const m=${safeJson(model)};const GS=${safeJson(LOKA_GRAPHIC_SYSTEM)};
const storyCanvas=document.getElementById('story');const legendStoryCanvas=document.getElementById('legendStory');const comparisonStoryCanvas=document.getElementById('comparisonStory');const feedCanvas=document.getElementById('feed');const storyCtx=storyCanvas.getContext('2d');const legendStoryCtx=legendStoryCanvas.getContext('2d');const comparisonStoryCtx=comparisonStoryCanvas?comparisonStoryCanvas.getContext('2d'):null;const feedCtx=feedCanvas.getContext('2d');let ctx=storyCtx;const INK=GS.palette.ink;const GOLD=GS.palette.gold;const CANVAS_FONT=GS.fontFamily;const LEGEND_FONT='Georgia,"Times New Roman",serif';const EMOJI_FONT='"Apple Color Emoji","Segoe UI Emoji","Noto Color Emoji",sans-serif';const STORY_HEADER_SAFE={logoX:50,logoCenterY:144,logoWidth:190,logoHeight:64,cityBaseline:158,dateBaseline:158};const FEED_HEADER={logoX:${LOKA_DAILY_FEED_FRAME.header.logoX},logoCenterY:${LOKA_DAILY_FEED_FRAME.header.logoCenterY},logoWidth:${LOKA_DAILY_FEED_FRAME.header.logoWidth},logoHeight:${LOKA_DAILY_FEED_FRAME.header.logoHeight},cityBaseline:${LOKA_DAILY_FEED_FRAME.header.cityBaseline},dateBaseline:${LOKA_DAILY_FEED_FRAME.header.dateBaseline}};
function normalizeText(value){return String(value??'').normalize('NFC').replace(/\\s+/g,' ').trim();}
function normalizeMultiline(value){return String(value??'').replace(/\\r\\n?/g,'\\n').normalize('NFC').split('\\n').map(line=>line.replace(/\\s+/g,' ').trim()).join('\\n').replace(/\\n{3,}/g,'\\n\\n').trim();}
function load(src,label='asset'){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('image_load_failed:'+label));i.src=src;});}
function font(size,weight){ctx.font=String(weight)+' '+String(size)+'px '+CANVAS_FONT;if('fontKerning' in ctx)ctx.fontKerning='normal';}
function drawFullTextLine(label,x,y,color,align){ctx.fillStyle=color;ctx.strokeStyle=color;ctx.textAlign=align;ctx.textBaseline='alphabetic';ctx.lineJoin=GS.text.lineJoin;ctx.miterLimit=GS.text.miterLimit;ctx.lineWidth=GS.text.strokeWidth;ctx.strokeText(label,x,y);ctx.fillText(label,x,y);}
function text(value,x,y,size,weight,color,align='left'){const label=normalizeText(value);ctx.save();font(size,weight);drawFullTextLine(label,x,y,color,align);ctx.restore();}
function trackedText(value,x,y,size,weight,color,tracking,align='center'){const chars=normalizeText(value).split('');ctx.save();font(size,weight);const widths=chars.map(ch=>ctx.measureText(ch).width);const total=widths.reduce((a,b)=>a+b,0)+Math.max(0,chars.length-1)*tracking;let cursor=align==='center'?x-total/2:align==='right'?x-total:x;ctx.fillStyle=color;ctx.textBaseline='alphabetic';for(let i=0;i<chars.length;i++){ctx.fillText(chars[i],cursor,y);cursor+=widths[i]+tracking;}ctx.restore();}
function fittedFontSize(value,maxWidth,maxSize,minSize,weight){const label=normalizeText(value);ctx.save();let size=maxSize;while(size>minSize){font(size,weight);if(ctx.measureText(label).width<=maxWidth)break;size-=1;}ctx.restore();return Math.max(minSize,size);}
function splitLines(value,maxWidth,maxLines,size,weight){const words=normalizeText(value).split(/\\s+/).filter(Boolean);ctx.save();font(size,weight);const lines=[];let line='';for(const word of words){const next=line?line+' '+word:word;if(line&&ctx.measureText(next).width>maxWidth){lines.push(line);line=word;if(lines.length>=maxLines){ctx.restore();return null;}}else line=next;}if(line)lines.push(line);ctx.restore();return lines.length<=maxLines?lines:null;}
function fitLines(value,maxWidth,maxLines,maxSize,minSize,weight){for(let size=maxSize;size>=minSize;size--){const lines=splitLines(value,maxWidth,maxLines,size,weight);if(lines)return{size,lines};}return{size:minSize,lines:[normalizeText(value)]};}
function wrap(value,x,y,maxWidth,lineHeight,size,weight,color,align='left',maxLines=2){ctx.save();font(size,weight);ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='alphabetic';const words=normalizeText(value).split(/\\s+/).filter(Boolean);let line='',yy=y,count=0;for(const word of words){const next=line?line+' '+word:word;if(ctx.measureText(next).width>maxWidth&&line){drawFullTextLine(line,x,yy,color,align);count++;if(count>=maxLines){ctx.restore();return;}line=word;yy+=lineHeight;}else line=next;}if(line&&count<maxLines)drawFullTextLine(line,x,yy,color,align);ctx.restore();}
function rr(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
function rgba(hex,a){const h=hex.replace('#','');const n=parseInt(h,16);return'rgba('+((n>>16)&255)+','+((n>>8)&255)+','+(n&255)+','+a+')';}
function dateLabel(date){try{return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',timeZone:m.timezone}).format(new Date(date+'T12:00:00')).toUpperCase();}catch{return String(date||'');}}
function drawCover(img,w,h){const iw=Math.max(1,img.naturalWidth||img.width||w);const ih=Math.max(1,img.naturalHeight||img.height||h);const scale=Math.max(w/iw,h/ih);const dw=iw*scale,dh=ih*scale;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);}
function box(x,y,w,h){const b=GS.glassBox;ctx.save();rr(x,y,w,h,b.radius);const g=ctx.createLinearGradient(x,y,x,y+h);g.addColorStop(0,b.fillTop);g.addColorStop(b.sheenRatio,b.fillMiddle);g.addColorStop(1,b.fillBottom);ctx.fillStyle=g;ctx.fill();ctx.strokeStyle=b.borderColor;ctx.lineWidth=b.borderWidth;ctx.stroke();ctx.save();rr(x+2,y+2,w-4,(h-4)*b.sheenClipRatio,b.insetRadius);ctx.clip();const sheen=ctx.createLinearGradient(x,y,x,y+h*b.sheenRatio);sheen.addColorStop(0,b.sheenTop);sheen.addColorStop(1,b.sheenBottom);ctx.fillStyle=sheen;ctx.fillRect(x+2,y+2,w-4,h*b.sheenRatio);ctx.restore();ctx.restore();}
function separator(x1,y1,x2,y2){ctx.save();ctx.strokeStyle=GS.separator.color;ctx.lineWidth=GS.separator.width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.restore();}
function drawImageCentered(img,cx,cy,w,h){const iw=Math.max(1,img.naturalWidth||img.width||w);const ih=Math.max(1,img.naturalHeight||img.height||h);const scale=Math.min(w/iw,h/ih);const dw=iw*scale,dh=ih*scale;ctx.drawImage(img,cx-dw/2,cy-dh/2,dw,dh);}
function pickHourlySlots(source){const wanted=[4,6,8,10,12,14,16,18,20,22];const pool=Array.isArray(source)?source:[];return wanted.map(hour=>pool.find(item=>Number(item.hour)===hour)||{hour,temperatureC:'—',condition:'nuageux',missing:true,pictogramUrl:m.hourly[0]?.pictogramUrl});}
function solarShiftLabel(value){if(value===null||value===undefined||value==='')return'';const delta=Number(value);if(!Number.isFinite(delta))return'';const rounded=Math.round(delta);if(rounded===0)return'0 min';return(rounded>0?'+':'−')+String(Math.abs(rounded))+' min';}
function drawLokaLogo(logo,x,centerY,maxWidth,maxHeight){if(!logo)return;const iw=Math.max(1,logo.naturalWidth||logo.width||maxWidth),ih=Math.max(1,logo.naturalHeight||logo.height||maxHeight),scale=Math.min(maxWidth/iw,maxHeight/ih),dw=iw*scale,dh=ih*scale;ctx.drawImage(logo,x,centerY-dh/2,dw,dh);}
function drawHeader(logo){drawLokaLogo(logo,STORY_HEADER_SAFE.logoX,STORY_HEADER_SAFE.logoCenterY,205,69);trackedText(String(m.city||'Tarnos').toUpperCase(),540,STORY_HEADER_SAFE.cityBaseline,28,760,INK,8,'center');text(dateLabel(m.date),1030,STORY_HEADER_SAFE.dateBaseline,24,700,INK,'right');}
function drawFeedHeader(logo){const s=GS.publicationVisualScale,h=GS.hierarchy;drawLokaLogo(logo,FEED_HEADER.logoX,FEED_HEADER.logoCenterY,FEED_HEADER.logoWidth*s*h.logo,FEED_HEADER.logoHeight*s*h.logo);trackedText(String(m.city||'Tarnos').toUpperCase(),540,FEED_HEADER.cityBaseline,${LOKA_DAILY_FEED_FRAME.header.citySize}*s*h.header,760,INK,8,'center');text(dateLabel(m.date),1030,FEED_HEADER.dateBaseline,${LOKA_DAILY_FEED_FRAME.header.dateSize}*s*h.header,700,INK,'right');}
function drawTitleBlock(title,x,oneLineY,twoLineY,maxWidth,maxSize,minSize,weight,color){ctx.save();font(maxSize,weight);const fitsOne=ctx.measureText(normalizeText(title)).width<=maxWidth;ctx.restore();if(fitsOne){text(title,x,oneLineY,maxSize,weight,color);return{lines:1,size:maxSize,bottom:oneLineY};}const fit=fitLines(title,maxWidth,2,Math.min(maxSize,52),minSize,weight);const lineHeight=Math.round(fit.size*.98);fit.lines.forEach((line,i)=>text(line,x,twoLineY+i*lineHeight,fit.size,weight,color));return{lines:fit.lines.length,size:fit.size,bottom:twoLineY+(fit.lines.length-1)*lineHeight};}
function drawSubtitleBlock(value,x,oneLineY,twoLineY,maxWidth,maxSize,minSize,color){ctx.save();font(maxSize,550);const fitsOne=ctx.measureText(normalizeText(value)).width<=maxWidth;ctx.restore();if(fitsOne){text(value,x,oneLineY,maxSize,550,color);return;}const fit=fitLines(value,maxWidth,2,Math.min(maxSize,23),minSize,550);const lineHeight=Math.round(fit.size*1.16);fit.lines.forEach((line,i)=>text(line,x,twoLineY+i*lineHeight,fit.size,550,color));}
function measureWidth(value,size,weight){ctx.save();font(size,weight);const width=ctx.measureText(normalizeText(value)).width;ctx.restore();return width;}
function centeredTitleLayout(value,maxWidth,maxSize,minSize,weight){const label=normalizeText(value),size=fittedFontSize(label,maxWidth,maxSize,minSize,weight),width=measureWidth(label,size,weight);return{lines:[label],size,lineHeight:Math.round(size*.98),width};}
function drawCenteredGeneralGroup(mainIcon,x,y,w,h,iconW,iconH,iconGap,tempGap,titleMax,titleMin,tempSize){const centerX=x+w/2,centerY=y+h/2,innerW=w-92,tempLabel=String(m.temps.minC)+'° — '+String(m.temps.maxC)+'°',tempWidth=measureWidth(tempLabel,tempSize,780);const titleBudget=Math.max(280,innerW-iconW-iconGap-tempGap-tempWidth);const titleLayout=centeredTitleLayout(m.scene.title,titleBudget,titleMax,titleMin,820);const groupW=iconW+iconGap+titleLayout.width+tempGap+tempWidth,startX=centerX-groupW/2,titleX=startX+iconW+iconGap,tempX=titleX+titleLayout.width+tempGap;drawImageCentered(mainIcon,startX+iconW/2,centerY,iconW,iconH);const titleStep=(titleLayout.lines.length-1)*titleLayout.lineHeight,firstBaseline=centerY-titleStep/2+titleLayout.size*.34;titleLayout.lines.forEach((line,i)=>text(line,titleX,firstBaseline+i*titleLayout.lineHeight,titleLayout.size,820,INK));text(tempLabel,tempX,centerY+tempSize*.34,tempSize,780,INK);}
function drawStoryGeneral(mainIcon){const x=44,y=200,w=992,h=150;box(x,y,w,h);drawCenteredGeneralGroup(mainIcon,x,y,w,h,160,130,28,40,55,34,53);}
function drawFeedGeneral(mainIcon){const x=${LOKA_DAILY_FEED_FRAME.title.x},y=${LOKA_DAILY_FEED_FRAME.title.y},w=${LOKA_DAILY_FEED_FRAME.title.width},h=${LOKA_DAILY_FEED_FRAME.title.height},s=GS.publicationVisualScale,hier=GS.hierarchy;box(x,y,w,h);drawCenteredGeneralGroup(mainIcon,x,y,w,h,150*s*hier.pictogram,122*s*hier.pictogram,26,36,48*s*hier.title,32*s,50*s*hier.metric);}
function drawStoryHours(slots,icons){const x=44,y=396,w=992,h=704;box(x,y,w,h);const colW=w/5;const rowTop=[424,770],rowBottom=[748,1074];separator(x+20,762,x+w-20,762);for(let row=0;row<2;row++){for(let i=1;i<5;i++){const sx=x+colW*i;separator(sx,rowTop[row]+18,sx,rowBottom[row]-18);}for(let c=0;c<5;c++){const idx=row*5+c,item=slots[idx];const cx=x+colW*(c+.5),base=rowTop[row];text(String(item.hour).padStart(2,'0')+'h',cx,base+52,28,700,INK,'center');if(!item.missing&&icons[idx])drawImageCentered(icons[idx],cx,base+141,136,110);text(String(item.temperatureC)+(item.missing?'':'°'),cx,base+242,48,780,INK,'center');}}}
function drawFeedHours(slots,icons){const x=50,y=336,w=980,h=500;box(x,y,w,h);const colW=w/5;const rowTop=[356,600],rowBottom=[576,820];separator(x+20,588,x+w-20,588);for(let row=0;row<2;row++){for(let i=1;i<5;i++){const sx=x+colW*i;separator(sx,rowTop[row]+10,sx,rowBottom[row]-10);}for(let c=0;c<5;c++){const idx=row*5+c,item=slots[idx];const cx=x+colW*(c+.5),base=rowTop[row];text(String(item.hour).padStart(2,'0')+'h',cx,base+32,24,700,INK,'center');if(!item.missing&&icons[idx])drawImageCentered(icons[idx],cx,base+95,110,90);text(String(item.temperatureC)+(item.missing?'':'°'),cx,base+186,40,780,INK,'center');}}}
function editorialAccent(x,y,width){ctx.save();ctx.strokeStyle=GOLD;ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+width,y);ctx.stroke();ctx.restore();}
function drawEditorialSummary(visual,x,y,w,h,primaryMax,primaryMin,secondaryMax,secondaryMin,accentWidth){const main=normalizeText(visual.primaryLine),secondary=normalizeText(visual.secondaryLine),left=x+${LOKA_EDITORIAL_SUMMARY_FRAME.insetX},maxWidth=w-${LOKA_EDITORIAL_SUMMARY_FRAME.insetX * 2},primaryWeight=720,secondaryWeight=650,primarySize=fittedFontSize(main,maxWidth,primaryMax,primaryMin,primaryWeight),secondaryFit=secondary?fitLines(secondary,maxWidth,${LOKA_EDITORIAL_SUMMARY_FRAME.secondary.maximumLines},secondaryMax,secondaryMin,secondaryWeight):{size:secondaryMax,lines:[]},secondaryLineHeight=Math.round(secondaryFit.size*${LOKA_EDITORIAL_SUMMARY_FRAME.secondaryLineHeightRatio}),secondaryHeight=secondaryFit.lines.length?secondaryFit.size+(secondaryFit.lines.length-1)*secondaryLineHeight:0,groupHeight=primarySize+${LOKA_EDITORIAL_SUMMARY_FRAME.accent.offsetBelowPrimary}+${LOKA_EDITORIAL_SUMMARY_FRAME.accent.lineWidth}+(secondaryFit.lines.length?${LOKA_EDITORIAL_SUMMARY_FRAME.gapAfterAccent}+secondaryHeight:0),top=y+(h-groupHeight)/2,primaryBaseline=top+primarySize,accentY=primaryBaseline+${LOKA_EDITORIAL_SUMMARY_FRAME.accent.offsetBelowPrimary};text(main,left,primaryBaseline,primarySize,primaryWeight,INK,'left');editorialAccent(left,accentY,accentWidth);if(secondaryFit.lines.length){const firstSecondaryBaseline=accentY+${LOKA_EDITORIAL_SUMMARY_FRAME.gapAfterAccent}+secondaryFit.size;secondaryFit.lines.forEach((line,i)=>text(line,left,firstSecondaryBaseline+i*secondaryLineHeight,secondaryFit.size,secondaryWeight,rgba(INK,.99),'left'));}}
function drawStoryComments(){const visual=m.storyVisual||m.visual;const x=44,y=1139,w=992,h=272;box(x,y,w,h);drawEditorialSummary(visual,x,y,w,h,37,23,28,19,58);}
function drawFeedComments(){const visual=m.feedVisual||m.visual,x=50,y=865,w=980,h=210,s=GS.publicationVisualScale,hier=GS.hierarchy;box(x,y,w,h);drawEditorialSummary(visual,x,y,w,h,29*s*hier.editorialTitle,20*s,21*s*hier.editorialDetail,17*s,52);}
function drawStorySolar(solarIcons){const x=44,y=1455,w=992,h=279;box(x,y,w,h);const colW=w/5;for(let i=1;i<5;i++)separator(x+colW*i,y+28,x+colW*i,y+h-28);const defs=[['AUBE','dawn',m.solar.dawn,null],['LEVER','sunrise',m.solar.sunrise,m.solar.sunriseDeltaMinutes],['MIDI SOLAIRE','noon',m.solar.solarNoon,null],['COUCHER','sunset',m.solar.sunset,m.solar.sunsetDeltaMinutes],['CRÉPUSCULE','dusk',m.solar.dusk,null]];defs.forEach((def,i)=>{const cx=x+colW*(i+.5);text(def[0],cx,1523,20,760,INK,'center');drawImageCentered(solarIcons[def[1]],cx,1610,116,88);text(def[2]||'—',cx,1692,36,700,INK,'center');const shift=solarShiftLabel(def[3]);if(shift)text(shift,cx,1724,21,650,rgba(INK,.88),'center');});}
function drawFeedSolar(solarIcons){const x=${LOKA_DAILY_FEED_FRAME.lowerBox.x},y=${LOKA_DAILY_FEED_FRAME.lowerBox.y},w=${LOKA_DAILY_FEED_FRAME.lowerBox.width},h=${LOKA_DAILY_FEED_FRAME.lowerBox.height};box(x,y,w,h);const colW=w/5;for(let i=1;i<5;i++)separator(x+colW*i,y+18,x+colW*i,y+h-18);const defs=[['AUBE','dawn',m.solar.dawn,null],['LEVER','sunrise',m.solar.sunrise,m.solar.sunriseDeltaMinutes],['MIDI SOLAIRE','noon',m.solar.solarNoon,null],['COUCHER','sunset',m.solar.sunset,m.solar.sunsetDeltaMinutes],['CRÉPUSCULE','dusk',m.solar.dusk,null]];defs.forEach((def,i)=>{const cx=x+colW*(i+.5);text(def[0],cx,1138,17,760,INK,'center');drawImageCentered(solarIcons[def[1]],cx,1192,90,68);text(def[2]||'—',cx,1252,31,700,INK,'center');const shift=solarShiftLabel(def[3]);if(shift)text(shift,cx,1280,18,650,rgba(INK,.84),'center');});}
function drawStorySignature(){text('Ici, aujourd’hui.',540,1810,25,680,INK,'center');ctx.save();ctx.strokeStyle=GOLD;ctx.lineWidth=1.4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(514,1834);ctx.lineTo(566,1834);ctx.stroke();ctx.restore();}
function drawFeedSignature(){text('Ici, aujourd’hui.',${LOKA_DAILY_FEED_FRAME.signature.x},${LOKA_DAILY_FEED_FRAME.signature.baseline},${LOKA_DAILY_FEED_FRAME.signature.size}*GS.publicationVisualScale*GS.hierarchy.signature,680,rgba(INK,${LOKA_DAILY_FEED_FRAME.signature.colorAlpha}),'center');ctx.save();ctx.strokeStyle=GOLD;ctx.lineWidth=${LOKA_DAILY_FEED_FRAME.signature.underlineWidth};ctx.lineCap='round';ctx.beginPath();ctx.moveTo(${LOKA_DAILY_FEED_FRAME.signature.underlineStartX},${LOKA_DAILY_FEED_FRAME.signature.underlineY});ctx.lineTo(${LOKA_DAILY_FEED_FRAME.signature.underlineEndX},${LOKA_DAILY_FEED_FRAME.signature.underlineY});ctx.stroke();ctx.restore();}
function renderStory(bg,logo,mainIcon,slots,hourIcons,solarIcons){ctx=storyCtx;ctx.clearRect(0,0,1080,1920);drawCover(bg,1080,1920);drawHeader(logo);drawStoryGeneral(mainIcon);drawStoryHours(slots,hourIcons);drawStoryComments();drawStorySolar(solarIcons);drawStorySignature();}
function drawComparisonTitle(){box(44,226,992,176);text(m.comparison.title,92,324,fittedFontSize(m.comparison.title,860,55,38,820),820,INK,'left');editorialAccent(94,354,58);}
function drawComparisonHero(icon){const p=m.comparison.presentation;box(44,438,992,550);drawImageCentered(icon,540,596,230,182);text(p.headline,540,790,fittedFontSize(p.headline,870,92,56,800),800,INK,'center');const fit=fitLines(p.subtitle,850,2,34,24,760),lineHeight=Math.round(fit.size*1.08);fit.lines.forEach((line,i)=>text(line,540,850+i*lineHeight,fit.size,760,INK,'center'));}
function drawComparisonValues(){const p=m.comparison.presentation;if(!p.comparison)return;const x=44,y=1024,w=992,h=286;box(x,y,w,h);separator(540,y+32,540,y+h-32);const items=[p.comparison.left,p.comparison.right];items.forEach((item,i)=>{const cx=i===0?292:788;text(item.value,cx,y+124,fittedFontSize(item.value,410,52,32,780),780,INK,'center');const fit=fitLines(item.label,390,2,24,18,720),lh=Math.round(fit.size*1.08);fit.lines.forEach((line,index)=>text(line,cx,y+185+index*lh,fit.size,720,INK,'center'));});}
function drawComparisonEditorial(){const p=m.comparison.presentation,y=p.comparison?1346:1040,h=p.comparison?300:420;box(44,y,992,h);drawEditorialSummary({primaryLine:p.editorialLine,secondaryLine:m.comparison.sourceNote},44,y,992,h,34,22,22,17,58);}
function renderComparisonStory(bg,logo,icon){if(!comparisonStoryCtx||!m.comparison)return;ctx=comparisonStoryCtx;ctx.clearRect(0,0,1080,1920);drawCover(bg,1080,1920);drawHeader(logo);drawComparisonTitle();drawComparisonHero(icon);drawComparisonValues();drawComparisonEditorial();drawStorySignature();ctx=storyCtx;}
function legendFont(size,weight=400){ctx.font=String(weight)+' '+String(size)+'px '+LEGEND_FONT;if('fontKerning' in ctx)ctx.fontKerning='normal';}
function splitLegendEmoji(value){const label=normalizeText(value);const match=label.match(/^(\\p{Extended_Pictographic}(?:\\uFE0F)?(?:\\u200D\\p{Extended_Pictographic}(?:\\uFE0F)?)*)\\s*(.*)$/u);return match?{emoji:match[1],text:match[2]}:{emoji:'',text:label};}
function legendParagraphLines(value,maxWidth,size,weight,firstLineInset=0){const words=normalizeText(value).split(/\\s+/).filter(Boolean);ctx.save();legendFont(size,weight);const lines=[];let line='';for(const word of words){const next=line?line+' '+word:word;const budget=maxWidth-(lines.length===0?firstLineInset:0);if(line&&ctx.measureText(next).width>budget){lines.push(line);line=word;}else line=next;}if(line)lines.push(line);ctx.restore();return lines;}
function legendLayout(value,maxWidth,maxHeight){const paragraphs=normalizeMultiline(value).split(/\\n\\s*\\n/).map(part=>part.trim()).filter(Boolean).slice(0,3);for(let size=72;size>=42;size--){const lineHeight=Math.round(size*1.19),separatorSpace=Math.round(size*1.82),emojiInset=Math.round(size*1.15);const blocks=paragraphs.map((part,index)=>{const parsed=index===0?splitLegendEmoji(part):{emoji:'',text:part};return{emoji:parsed.emoji,lines:legendParagraphLines(parsed.text,maxWidth,size,400,index===0&&parsed.emoji?emojiInset:0)};});const lines=blocks.reduce((sum,block)=>sum+block.lines.length,0);const height=lines*lineHeight+Math.max(0,blocks.length-1)*separatorSpace;if(height<=maxHeight)return{size,lineHeight,separatorSpace,emojiInset,blocks,height};}const size=42,lineHeight=50,separatorSpace=76,emojiInset=48,blocks=paragraphs.map((part,index)=>{const parsed=index===0?splitLegendEmoji(part):{emoji:'',text:part};return{emoji:parsed.emoji,lines:legendParagraphLines(parsed.text,maxWidth,size,400,index===0&&parsed.emoji?emojiInset:0)};});const lines=blocks.reduce((sum,block)=>sum+block.lines.length,0);return{size,lineHeight,separatorSpace,emojiInset,blocks,height:lines*lineHeight+Math.max(0,blocks.length-1)*separatorSpace};}
function drawLegendSerifLine(value,x,y,size){ctx.save();legendFont(size,400);ctx.fillStyle=INK;ctx.strokeStyle=INK;ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.lineJoin='round';ctx.miterLimit=2;ctx.lineWidth=.34;ctx.strokeText(value,x,y);ctx.fillText(value,x,y);ctx.restore();}
function drawLegendEmoji(value,x,y,size){if(!value)return;ctx.save();ctx.font=String(Math.round(size*.82))+'px '+EMOJI_FONT;ctx.textAlign='left';ctx.textBaseline='alphabetic';ctx.fillText(value,x,y);ctx.restore();}
function drawLegendAccent(y){ctx.save();ctx.strokeStyle=GOLD;ctx.lineWidth=4;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(455,y);ctx.lineTo(625,y);ctx.stroke();ctx.restore();}
function drawLegendPanel(){const value=m.legendText||[m.social?.paragraph1,m.social?.paragraph2].filter(Boolean).join('\\n\\n');const panelX=44,panelY=330,panelW=992,panelH=1260,paddingX=58,paddingY=72,x=panelX+paddingX,w=panelW-paddingX*2,areaTop=panelY+paddingY,areaHeight=panelH-paddingY*2;box(panelX,panelY,panelW,panelH);const layout=legendLayout(value,w,areaHeight);let yy=areaTop+Math.max(0,(areaHeight-layout.height)/2)+layout.size;layout.blocks.forEach((block,index)=>{block.lines.forEach((line,lineIndex)=>{const inset=index===0&&lineIndex===0&&block.emoji?layout.emojiInset:0;if(index===0&&lineIndex===0&&block.emoji)drawLegendEmoji(block.emoji,x,yy,layout.size);drawLegendSerifLine(line,x+inset,yy,layout.size);yy+=layout.lineHeight;});if(index<layout.blocks.length-1){const lineY=yy+Math.round(layout.separatorSpace*.24);drawLegendAccent(lineY);yy+=layout.separatorSpace;}});}
function renderLegendStory(bg,logo){ctx=legendStoryCtx;ctx.clearRect(0,0,1080,1920);drawCover(bg,1080,1920);drawHeader(logo);drawLegendPanel();drawStorySignature();ctx=storyCtx;}
function renderFeed(bg,logo,mainIcon,slots,hourIcons,solarIcons){ctx=feedCtx;ctx.clearRect(0,0,${LOKA_DAILY_FEED_FRAME.width},${LOKA_DAILY_FEED_FRAME.height});drawCover(bg,${LOKA_DAILY_FEED_FRAME.width},${LOKA_DAILY_FEED_FRAME.height});drawFeedHeader(logo);drawFeedGeneral(mainIcon);drawFeedHours(slots,hourIcons);drawFeedComments();drawFeedSolar(solarIcons);drawFeedSignature();ctx=storyCtx;}
async function draw(){window.__LOKA_RENDER_STATUS={started:true,storyRendered:false,legendRendered:false,comparisonRendered:false,feedRendered:false,error:null};const slots=pickHourlySlots(m.hourly);const bg=await load(m.masterUrl,'background');const logo=await load(m.brand.logoUrl,'logo');const mainIcon=await load(m.scene.pictogramUrl,'main_pictogram');const comparisonIcon=m.comparison?await load(m.comparison.pictogramUrl,'comparison_pictogram'):null;const hourIcons=await Promise.all(slots.map((item,index)=>load(item.pictogramUrl,'hourly_pictogram_'+index)));const solarIcons={dawn:await load(m.solarPictograms.dawn,'solar_dawn'),sunrise:await load(m.solarPictograms.sunrise,'solar_sunrise'),noon:await load(m.solarPictograms.noon,'solar_noon'),sunset:await load(m.solarPictograms.sunset,'solar_sunset'),dusk:await load(m.solarPictograms.dusk,'solar_dusk')};renderStory(bg,logo,mainIcon,slots,hourIcons,solarIcons);window.__LOKA_RENDER_STATUS.storyRendered=true;renderLegendStory(bg,logo);window.__LOKA_RENDER_STATUS.legendRendered=true;if(comparisonIcon){renderComparisonStory(bg,logo,comparisonIcon);window.__LOKA_RENDER_STATUS.comparisonRendered=true;}renderFeed(bg,logo,mainIcon,slots,hourIcons,solarIcons);window.__LOKA_RENDER_STATUS.feedRendered=true;window.__LOKA_RENDER_STATUS.rendered=true;window.__LOKA_EDITORIAL_AUDIT={sceneId:m.scene.id,title:m.scene.canonicalTitle,displayTitle:m.scene.title,rendererReclassified:false};window.__LOKA_BRAND_AUDIT={logoUrl:m.brand.logoUrl};window.__LOKA_PICTOGRAM_AUDIT={version:m.pictogramLibrary.version,ink:m.pictogramLibrary.ink,gold:m.pictogramLibrary.gold,mainSceneId:m.scene.id};}
function fallbackCopy(value){const area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();area.setSelectionRange(0,area.value.length);let ok=false;try{ok=document.execCommand('copy');}catch{}area.remove();return ok;}
async function copyText(value,label){let ok=false;try{if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(value);ok=true;}}catch{}if(!ok)ok=fallbackCopy(value);const status=document.getElementById('copyStatus');status.textContent=ok?label+' copié.':'Copie impossible : sélectionne le texte manuellement.';setTimeout(()=>{if(status.textContent.startsWith(label))status.textContent='';},1800);}
function canvasFile(targetCanvas,suffix){return new Promise(resolve=>targetCanvas.toBlob(blob=>resolve(blob?new File([blob],'loka-'+String(m.date||'meteo')+'-'+suffix+'.png',{type:'image/png'}):null),'image/png'));}
function fallbackDownload(file){const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function shareCanvas(targetCanvas,suffix){const file=await canvasFile(targetCanvas,suffix);if(!file)return;if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({files:[file],title:'LOKA!'});return;}catch(error){if(error?.name==='AbortError')return;}}fallbackDownload(file);}
document.getElementById('shareStory').onclick=()=>shareCanvas(storyCanvas,'story');document.getElementById('shareLegendStory').onclick=()=>shareCanvas(legendStoryCanvas,'story-legende');if(comparisonStoryCanvas)document.getElementById('shareComparisonStory').onclick=()=>shareCanvas(comparisonStoryCanvas,'story-comparaison');document.getElementById('shareFeed').onclick=()=>shareCanvas(feedCanvas,'post');document.getElementById('captionText').textContent=m.social.caption;document.getElementById('hashtagsText').textContent=m.social.hashtags;document.getElementById('copyCaption').onclick=()=>copyText(m.social.caption,'Légende');document.getElementById('copyHashtags').onclick=()=>copyText(m.social.hashtags,'Hashtags');document.getElementById('copyAll').onclick=()=>copyText(m.social.caption+'\\n\\n'+m.social.hashtags,'Légende + hashtags');
draw().catch(error=>{window.__LOKA_RENDER_STATUS={started:true,rendered:false,error:String(error)};document.getElementById('summary').textContent='Erreur de rendu : '+String(error);});
</script><!--LOKA_EDITORIAL_SCRIPT_MOUNT--></body></html>`;
}
