const STYLE = `<style>
.v3-parallel{background:#fff;border-radius:24px;padding:18px;margin:4px 0 18px}.v3-parallel-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v3-parallel h2{font-size:18px;line-height:1.15;margin:6px 0}.v3-parallel p{font-size:11px;line-height:1.5;color:#73716c;margin:0}.v3-parallel-badge{font-size:9px;font-weight:800;letter-spacing:.08em;color:#24653a;background:#eaf6ee;padding:6px 8px;border-radius:999px;white-space:nowrap}.v3-parallel-compare{margin-top:14px;padding:12px;border-radius:18px;background:#f5f4f1}.v3-parallel-compare strong{display:block;font-size:12px;margin-bottom:4px}.v3-parallel-frame{display:block;width:100%;height:1690px;border:0;border-radius:20px;background:#ecebe7;margin-top:12px}.v3-parallel-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.v3-parallel-actions a{border-radius:14px;padding:13px 10px;text-decoration:none;text-align:center;font:650 13px/1 -apple-system,BlinkMacSystemFont,sans-serif}.v3-parallel-actions .primary{background:#171715;color:#fff}.v3-parallel-actions .secondary{background:#f1f1ee;color:#171715}@media(max-width:420px){.v3-parallel-top{display:block}.v3-parallel-badge{display:inline-block;margin-bottom:8px}.v3-parallel-actions{grid-template-columns:1fr}.v3-parallel-frame{height:1630px}}
</style>`;

const MARKUP = `<section class="v3-parallel" id="v3ParallelStudio"><div class="v3-parallel-top"><div><p>COMPARAISON DE FORMAT</p><h2>Publication V2 actuelle ↔ Carrousel V3</h2><p>La Publication V2 affichée juste au-dessus reste le format officiel. Les deux pages ci-dessous sont uniquement des previews et exports manuels.</p></div><span class="v3-parallel-badge">V3 PARALLÈLE · SAFE</span></div><div class="v3-parallel-compare"><strong>Référence V2</strong><p>Le canvas « PUBLICATION » 1080 × 1440 situé au-dessus est la référence de production à comparer avec Page 1 et Page 2.</p></div><iframe class="v3-parallel-frame" title="Carrousel V3 parallèle" src="/instagram-v3-preview?embed=1" loading="lazy"></iframe><div class="v3-parallel-actions"><a class="primary" href="/instagram-v3-preview" target="_blank" rel="noopener">Ouvrir le V3 en plein écran</a><a class="secondary" href="#v3ParallelStudio">Comparer ici</a></div></section>`;

export function enhanceInstagramWithV3ParallelStudio(html: string): string {
  const marker = "<!--LOKA_EDITORIAL_STUDIO_MOUNT-->";
  if (!html.includes(marker)) throw new Error("instagram_v3_parallel_marker_missing");
  return html.replace("</style><!--LOKA_EDITORIAL_STYLE_MOUNT-->", `</style>${STYLE}<!--LOKA_EDITORIAL_STYLE_MOUNT-->`).replace(marker, `${MARKUP}${marker}`);
}
