function safeJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");
}

export function renderInstagramRecovery(citySlug: string, reason: string): string {
  const data = safeJson({ citySlug, reason });
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>LOKA! — Préparer Instagram</title><style>
:root{--navy:#12264A;--gold:#FDB515;--paper:#F3F1EC;--muted:#6E7580;--green:#24653A;--red:#9C2F2F}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--navy);font-family:-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;padding:max(20px,env(safe-area-inset-top)) 16px max(30px,env(safe-area-inset-bottom));min-height:100vh;display:grid;place-items:center}.card{width:min(100%,520px);background:#fff;border-radius:30px;padding:26px;box-shadow:0 20px 70px rgba(18,38,74,.12)}.brand{font-size:18px;font-weight:900;letter-spacing:.02em;color:var(--navy)}.eyebrow{margin-top:22px;color:var(--gold);font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}h1{font-size:30px;line-height:1.05;margin:8px 0 12px;letter-spacing:-.035em}.lead{font-size:15px;line-height:1.55;color:#4f5968;margin:0 0 22px}.state{background:#F7F8FA;border-radius:18px;padding:14px 16px;margin-bottom:16px;font-size:13px;line-height:1.45}.state strong{display:block;color:var(--navy);margin-bottom:3px}.remembered{color:var(--green)}.field{display:none;margin:14px 0}.field.visible{display:block}label{display:block;font-size:12px;font-weight:750;margin-bottom:7px}input{width:100%;border:1px solid #D8DDE5;border-radius:14px;padding:14px 15px;font-size:16px;color:var(--navy);background:#fff;outline:none}input:focus{border-color:#9DA9BB;box-shadow:0 0 0 3px rgba(18,38,74,.06)}button{width:100%;border:0;border-radius:15px;padding:16px 14px;font-size:15px;font-weight:850;cursor:pointer}.primary{background:var(--navy);color:#fff}.primary:disabled{opacity:.55;cursor:wait}.link{margin-top:11px;background:transparent;color:#747C88;padding:10px;font-size:12px}.status{min-height:44px;margin-top:14px;padding:12px 14px;border-radius:14px;background:#F7F8FA;color:#586273;font-size:13px;line-height:1.45}.status.ok{background:#EDF6EF;color:var(--green)}.status.error{background:#FBEEEE;color:var(--red)}.small{font-size:11px;color:#9097A1;line-height:1.5;margin-top:16px}.spinner{display:inline-block;width:13px;height:13px;border:2px solid rgba(255,255,255,.35);border-top-color:#fff;border-radius:50%;vertical-align:-2px;margin-right:8px;animation:spin .8s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}
</style></head><body><main class="card"><div class="brand">LOKA!</div><div class="eyebrow">Studio Instagram</div><h1>Préparer les visuels du jour</h1><p class="lead">Aucune scène V24 officielle n’est encore disponible. Tu peux la générer, la valider et l’officialiser ici en une seule action.</p><div class="state" id="authState"><strong>Accès administrateur</strong><span id="authText">Vérification de cet appareil…</span></div><div class="field" id="tokenField"><label for="token">Mot de passe administrateur</label><input id="token" type="password" autocomplete="current-password" placeholder="ADMIN_TOKEN"></div><button class="primary" id="prepare">Préparer les visuels maintenant</button><button class="link" id="forget" type="button">Oublier le mot de passe enregistré sur cet appareil</button><div class="status" id="status">Une fois prêts, la page Instagram s’ouvrira automatiquement.</div><div class="small">Le mot de passe n’est jamais placé dans l’URL ni envoyé ailleurs : il reste uniquement dans le stockage local de ce navigateur. Motif technique actuel : <span id="reason"></span>.</div></main><script>
const DATA=${data};
const STORAGE_KEY='loka_admin_token_v2';
const tokenField=document.getElementById('tokenField');
const tokenInput=document.getElementById('token');
const authText=document.getElementById('authText');
const prepare=document.getElementById('prepare');
const forget=document.getElementById('forget');
const status=document.getElementById('status');
document.getElementById('reason').textContent=DATA.reason;
function storedToken(){try{return localStorage.getItem(STORAGE_KEY)||'';}catch{return'';}}
function setStoredToken(value){try{if(value)localStorage.setItem(STORAGE_KEY,value);else localStorage.removeItem(STORAGE_KEY);}catch{}}
function refreshAuth(){const saved=storedToken();tokenField.classList.toggle('visible',!saved);authText.textContent=saved?'Accès mémorisé sur cet appareil.':'Mot de passe requis une seule fois sur cet appareil.';authText.className=saved?'remembered':'';forget.style.display=saved?'block':'none';}
function show(message,kind=''){status.textContent=message;status.className='status'+(kind?' '+kind:'');}
forget.onclick=()=>{setStoredToken('');tokenInput.value='';refreshAuth();show('Mot de passe oublié sur cet appareil.');tokenInput.focus();};
prepare.onclick=async()=>{const token=storedToken()||tokenInput.value.trim();if(!token){tokenField.classList.add('visible');show('Entre ton mot de passe administrateur pour cette première utilisation.','error');tokenInput.focus();return;}prepare.disabled=true;prepare.innerHTML='<span class="spinner"></span>Préparation en cours…';show('LOKA interroge les modèles, valide la scène V24 puis prépare Story et Publication.');try{const response=await fetch('/api/admin/instagram/prepare?city='+encodeURIComponent(DATA.citySlug),{method:'POST',headers:{authorization:'Bearer '+token}});let body={};try{body=await response.json();}catch{}if(response.status===401){setStoredToken('');refreshAuth();show('Mot de passe incorrect. Saisis-le à nouveau.','error');return;}if(!response.ok||!body.ok){show('Préparation impossible : '+String(body.error||('HTTP '+response.status))+'.','error');return;}setStoredToken(token);refreshAuth();const scene=body.scene?(' · '+String(body.scene.id).padStart(2,'0')+' '+body.scene.label):'';show('Visuels prêts'+scene+'. Ouverture du Studio Instagram…','ok');setTimeout(()=>location.replace('/instagram'),450);}catch(error){show('Erreur réseau : '+String(error),'error');}finally{prepare.disabled=false;prepare.textContent='Préparer les visuels maintenant';}};
refreshAuth();
</script></body></html>`;
}
