const STYLE = `<style>
.v3-parallel{background:#fff;border-radius:24px;padding:18px;margin:4px 0 18px}.v3-parallel-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v3-parallel h2{font-size:18px;line-height:1.15;margin:6px 0}.v3-parallel p{font-size:11px;line-height:1.5;color:#73716c;margin:0}.v3-parallel-badge{font-size:9px;font-weight:800;letter-spacing:.08em;color:#24653a;background:#eaf6ee;padding:6px 8px;border-radius:999px;white-space:nowrap}.v3-parallel-compare{margin-top:14px;padding:12px;border-radius:18px;background:#f5f4f1}.v3-parallel-compare strong{display:block;font-size:12px;margin-bottom:4px}.v3-parallel-frame{display:block;width:100%;height:1690px;border:0;border-radius:20px;background:#ecebe7;margin-top:12px}.v3-parallel-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.v3-parallel-actions a{border-radius:14px;padding:13px 10px;text-decoration:none;text-align:center;font:650 13px/1 -apple-system,BlinkMacSystemFont,sans-serif}.v3-parallel-actions .primary{background:#171715;color:#fff}.v3-parallel-actions .secondary{background:#f1f1ee;color:#171715}@media(max-width:420px){.v3-parallel-top{display:block}.v3-parallel-badge{display:inline-block;margin-bottom:8px}.v3-parallel-actions{grid-template-columns:1fr}.v3-parallel-frame{height:1630px}}
</style>`;

const MARKUP = `<section class="v3-parallel" id="v3ParallelStudio"><div class="v3-parallel-top"><div><p>COMPARAISON DE FORMAT</p><h2>Publication V2 actuelle ↔ Carrousel V3</h2><p>La Publication V2 affichée juste au-dessus reste le format officiel. Les deux pages ci-dessous sont uniquement des previews et exports manuels.</p></div><span class="v3-parallel-badge">V3 PARALLÈLE · SAFE</span></div><div class="v3-parallel-compare"><strong>Référence V2</strong><p>Le canvas « PUBLICATION » 1080 × 1440 situé au-dessus est la référence de production à comparer avec Page 1 et Page 2.</p></div><iframe class="v3-parallel-frame" title="Carrousel V3 parallèle" src="/instagram-v3-preview?embed=1" loading="lazy"></iframe><div class="v3-parallel-actions"><a class="primary" href="/instagram-v3-preview" target="_blank" rel="noopener">Ouvrir le V3 en plein écran</a><a class="secondary" href="#v3ParallelStudio">Comparer ici</a></div></section>`;

export function enhanceInstagramWithV3ParallelStudio(html: string): string {
  const marker = "<!--LOKA_EDITORIAL_STUDIO_MOUNT-->";
  if (!html.includes(marker)) throw new Error("instagram_v3_parallel_marker_missing");
  return html.replace("</style><!--LOKA_EDITORIAL_STYLE_MOUNT-->", `</style>${STYLE}<!--LOKA_EDITORIAL_STYLE_MOUNT-->`).replace(marker, `${MARKUP}${marker}`);
}

const PRIMARY_STYLE = `<style>
.v3-primary{background:#fff;border-radius:24px;padding:18px;margin:0 0 18px;box-shadow:0 12px 45px rgba(0,0,0,.06)}.v3-primary-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v3-primary h2{font-size:21px;line-height:1.12;margin:6px 0}.v3-primary p{font-size:11px;line-height:1.5;color:#73716c;margin:0}.v3-primary-badge{font-size:9px;font-weight:850;letter-spacing:.08em;color:#164e2d;background:#e7f5eb;padding:7px 9px;border-radius:999px;white-space:nowrap}.v3-primary-status{margin-top:14px;padding:12px 14px;border-radius:18px;background:#f3f8f4;border:1px solid #e3eee6}.v3-primary-status strong{display:block;font-size:12px;margin-bottom:4px}.v3-primary-frame{display:block;width:100%;height:1690px;border:0;border-radius:20px;background:#ecebe7;margin-top:12px}.v3-primary-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.v3-primary-actions a{border-radius:14px;padding:13px 10px;text-decoration:none;text-align:center;font:650 13px/1 -apple-system,BlinkMacSystemFont,sans-serif}.v3-primary-actions .primary{background:#171715;color:#fff}.v3-primary-actions .secondary{background:#f1f1ee;color:#171715}.v2-current-label{font-size:11px;font-weight:800;letter-spacing:.09em;color:#73716c;margin:2px 4px 10px}.v2-fallback-note{background:#fff7dd;color:#76530a;border-radius:18px;padding:12px 14px;margin:2px 0 12px;font-size:11px;line-height:1.5}.v2-fallback-note strong{display:block;font-size:12px;margin-bottom:3px}@media(max-width:420px){.v3-primary-top{display:block}.v3-primary-badge{display:inline-block;margin-bottom:8px}.v3-primary-actions{grid-template-columns:1fr}.v3-primary-frame{height:1630px}}
</style>`;

const PRIMARY_MARKUP = `<section class="v3-primary" id="v3PrimaryStudio"><div class="v3-primary-top"><div><p>FORMAT PRINCIPAL DU STUDIO</p><h2>Carrousel V3 · Page 1 + Page 2</h2><p>Le carrousel V3 devient la référence de travail et d’export manuel dans le Studio. Les Stories actuelles restent inchangées.</p></div><span class="v3-primary-badge">V3 ACTIF · MANUEL</span></div><div class="v3-primary-status"><strong>Bascule contrôlée</strong><p>La publication automatique reste encore sur le moteur V2. La Publication V2 est conservée plus bas comme fallback de sécurité.</p></div><iframe class="v3-primary-frame" title="Carrousel V3 principal" src="/instagram-v3-preview?embed=1&studio=primary" loading="eager"></iframe><div class="v3-primary-actions"><a class="primary" href="/instagram-v3-preview?studio=primary" target="_blank" rel="noopener">Ouvrir le V3 en plein écran</a><a class="secondary" href="#v2FallbackPublication">Voir le fallback V2</a></div></section><div class="v2-current-label">STORIES ACTUELLES · V2</div>`;

export function enhanceInstagramWithV3PrimaryStudio(html: string): string {
  const styleMarker = "</style><!--LOKA_EDITORIAL_STYLE_MOUNT-->";
  const storyMarker = '<div class="visual-card"><div class="visual-head"><div class="visual-title">STORY / REEL</div>';
  const publicationMarker = '<div class="visual-card"><div class="visual-head"><div class="visual-title">PUBLICATION</div>';
  if (!html.includes(styleMarker)) throw new Error("instagram_v3_primary_style_marker_missing");
  if (!html.includes(storyMarker)) throw new Error("instagram_v3_primary_story_marker_missing");
  if (!html.includes(publicationMarker)) throw new Error("instagram_v3_primary_publication_marker_missing");
  let result = html.replace(styleMarker, `</style>${PRIMARY_STYLE}<!--LOKA_EDITORIAL_STYLE_MOUNT-->`);
  result = result.replace(storyMarker, `${PRIMARY_MARKUP}${storyMarker}`);
  result = result.replace(publicationMarker, `<div class="v2-fallback-note" id="v2FallbackPublication"><strong>Publication V2 · fallback de sécurité</strong>Ce visuel reste disponible manuellement et continue d’être la référence de l’automatisation tant que la bascule V3 de publication n’est pas validée.</div><div class="visual-card"><div class="visual-head"><div class="visual-title">PUBLICATION V2 · FALLBACK</div>`);
  return result;
}



const OFFICIAL_STYLE = `<style>
.v3-official{background:#fff;border-radius:24px;padding:18px;margin:0 0 18px;box-shadow:0 12px 45px rgba(0,0,0,.06)}.v3-official-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v3-official h2{font-size:21px;line-height:1.12;margin:6px 0}.v3-official p{font-size:11px;line-height:1.5;color:#73716c;margin:0}.v3-official-badge{font-size:9px;font-weight:850;letter-spacing:.08em;color:#164e2d;background:#e7f5eb;padding:7px 9px;border-radius:999px;white-space:nowrap}.v3-official-status{margin-top:14px;padding:12px 14px;border-radius:18px;background:#f3f8f4;border:1px solid #d7e9dc}.v3-official-status strong{display:block;font-size:12px;margin-bottom:4px}.v3-official-frame{display:block;width:100%;height:1690px;border:0;border-radius:20px;background:#ecebe7;margin-top:12px}.v3-official-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.v3-official-actions a{border-radius:14px;padding:13px 10px;text-decoration:none;text-align:center;font:650 13px/1 -apple-system,BlinkMacSystemFont,sans-serif}.v3-official-actions .primary{background:#171715;color:#fff}.v3-official-actions .secondary{background:#f1f1ee;color:#171715}.v2-rollback-label{font-size:11px;font-weight:800;letter-spacing:.09em;color:#73716c;margin:2px 4px 10px}.v2-rollback-note{background:#fff7dd;color:#76530a;border-radius:18px;padding:12px 14px;margin:2px 0 12px;font-size:11px;line-height:1.5}.v2-rollback-note strong{display:block;font-size:12px;margin-bottom:3px}@media(max-width:420px){.v3-official-top{display:block}.v3-official-badge{display:inline-block;margin-bottom:8px}.v3-official-actions{grid-template-columns:1fr}.v3-official-frame{height:1630px}}
</style>`;

const OFFICIAL_MARKUP = `<section class="v3-official" id="v3OfficialStudio"><div class="v3-official-top"><div><p>FORMAT OFFICIEL DE PUBLICATION MANUELLE</p><h2>Carrousel V3 · Page 1 + Page 2</h2><p>Le carrousel V3 devient la référence officielle pour les exports et publications manuelles depuis le Studio. Les Stories actuelles restent inchangées.</p></div><span class="v3-official-badge">V3 OFFICIEL · MANUEL</span></div><div class="v3-official-status"><strong>Bascule officielle contrôlée</strong><p>L’automatisation Instagram reste encore sur le format V2. Le visuel V2 est conservé plus bas comme rollback immédiat en cas de besoin.</p></div><iframe class="v3-official-frame" title="Carrousel V3 officiel" src="/instagram-v3-preview?embed=1&studio=official" loading="eager"></iframe><div class="v3-official-actions"><a class="primary" href="/instagram-v3-preview?studio=official" target="_blank" rel="noopener">Ouvrir / exporter le V3 officiel</a><a class="secondary" href="#v2RollbackPublication">Rollback V2</a></div></section><div class="v2-rollback-label">STORIES ACTUELLES · V2</div>`;

export function enhanceInstagramWithV3OfficialStudio(html: string): string {
  const styleMarker = "</style><!--LOKA_EDITORIAL_STYLE_MOUNT-->";
  const storyMarker = '<div class="visual-card"><div class="visual-head"><div class="visual-title">STORY / REEL</div>';
  const publicationMarker = '<div class="visual-card"><div class="visual-head"><div class="visual-title">PUBLICATION</div>';
  if (!html.includes(styleMarker)) throw new Error("instagram_v3_official_style_marker_missing");
  if (!html.includes(storyMarker)) throw new Error("instagram_v3_official_story_marker_missing");
  if (!html.includes(publicationMarker)) throw new Error("instagram_v3_official_publication_marker_missing");
  let result = html.replace(styleMarker, `</style>${OFFICIAL_STYLE}<!--LOKA_EDITORIAL_STYLE_MOUNT-->`);
  result = result.replace(storyMarker, `${OFFICIAL_MARKUP}${storyMarker}`);
  result = result.replace(publicationMarker, `<div class="v2-rollback-note" id="v2RollbackPublication"><strong>Publication V2 · rollback immédiat</strong>Ce visuel reste disponible pour un retour manuel immédiat et demeure la référence de l’automatisation tant que l’activation automatique du V3 n’est pas validée.</div><div class="visual-card"><div class="visual-head"><div class="visual-title">PUBLICATION V2 · ROLLBACK</div>`);
  return result;
}
