import type { CityConfig, OfficialPublicPayloadV24, VisualIcon, HourlyCondition } from "../types";
import { solarPresentation } from "./solarTimes";

function safeJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");
}

export function renderInstagramOfficial24(payload: OfficialPublicPayloadV24, city: CityConfig): string {
  if (
    payload.editorial.scene.id !== payload.scene.id ||
    payload.editorial.scene.title !== payload.scene.label ||
    payload.editorial.scene.visualIcon !== payload.scene.visualIcon
  ) {
    throw new Error("instagram_editorial_scene_mismatch");
  }

  const model = {
    city: payload.city,
    date: payload.date,
    timezone: city.timezone,
    masterUrl: payload.scene.masterUrl,
    scene: {
      id: payload.editorial.scene.id,
      title: payload.editorial.scene.title,
      visualIcon: payload.editorial.scene.visualIcon as VisualIcon
    },
    visual: payload.editorial.visual,
    social: payload.editorial.social,
    temps: payload.temperatures,
    hourly: payload.hourly as Array<{ hour: number; temperatureC: number; condition: HourlyCondition; precipitationMm: number }>,
    solar: solarPresentation(city, payload.date)
  };

  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>LOKA! — Studio Instagram V2</title><style>
:root{--ink:#171715;--muted:#73716c;--paper:#ecebe7}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;padding:max(14px,env(safe-area-inset-top)) 12px max(26px,env(safe-area-inset-bottom))}.wrap{width:min(100%,580px);margin:auto}.toolbar{background:#fff;border-radius:24px;padding:18px;margin-bottom:14px}.topline{display:flex;align-items:center;justify-content:space-between;gap:12px}.brand{font-size:12px;font-weight:760;letter-spacing:.16em}.badge{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:#24653a;background:#e8f3ea;padding:6px 8px;border-radius:999px}h1{font-size:23px;line-height:1.08;margin:14px 0 5px}.muted{font-size:12px;line-height:1.5;color:var(--muted)}.visual-card{margin:0 0 18px}.visual-head{display:flex;align-items:end;justify-content:space-between;gap:12px;padding:0 4px 9px}.visual-title{font-size:14px;font-weight:760;letter-spacing:.08em}.visual-size{font-size:11px;color:var(--muted)}button{border:0;border-radius:14px;padding:14px 10px;text-align:center;font:650 13px/1 -apple-system,BlinkMacSystemFont,sans-serif;cursor:pointer}.primary{background:#171715;color:#fff;width:100%;margin-top:10px}.secondary{background:#f1f1ee;color:#171715}.canvas-wrap{background:#d8d8d4;border-radius:26px;overflow:hidden;box-shadow:0 18px 70px rgba(0,0,0,.14)}canvas{display:block;width:100%;height:auto}.note{text-align:center;font-size:11px;color:#8d8983;line-height:1.45;padding:2px 12px 14px}.caption-card{background:#fff;border-radius:24px;padding:18px;margin:4px 0 18px}.caption-title{font-size:14px;font-weight:760;letter-spacing:.08em}.caption-help{font-size:11px;line-height:1.4;color:var(--muted);margin-top:4px}.copy-label{font-size:11px;font-weight:760;letter-spacing:.08em;color:#5f5d58;margin:16px 0 7px}.copy-box{margin:0;white-space:pre-wrap;word-break:break-word;background:#f4f3f0;border-radius:16px;padding:14px;font:500 14px/1.55 -apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;color:#171715}.copy-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:9px}.copy-actions button{margin:0;width:100%}.copy-all{margin-top:10px}.copy-status{min-height:18px;padding-top:8px;text-align:center;font-size:11px;color:#24653a}@media(max-width:420px){.copy-actions{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="toolbar"><div class="topline"><div class="brand">LOKA!</div><div class="badge">Météo officielle · V24</div></div><h1>Studio Instagram</h1><div class="muted" id="summary">${payload.city} · scène ${String(payload.scene.id).padStart(2,"0")}</div></div>
<div class="visual-card"><div class="visual-head"><div class="visual-title">STORY / REEL</div><div class="visual-size">1080 × 1920 · 9:16</div></div><div class="canvas-wrap"><canvas id="story" width="1080" height="1920"></canvas></div><button class="primary" id="shareStory">Partager / enregistrer la Story</button></div>
<div class="visual-card"><div class="visual-head"><div class="visual-title">PUBLICATION</div><div class="visual-size">1080 × 1440 · 3:4</div></div><div class="canvas-wrap"><canvas id="feed" width="1080" height="1440"></canvas></div><button class="primary" id="shareFeed">Partager / enregistrer la Publication</button></div>
<div class="note">Composition graphique restaurée sur le gabarit LOKA! de référence. La météo et les textes proviennent exclusivement de l’Editorial Engine V2.</div>
<div class="caption-card"><div class="caption-title">LÉGENDE INSTAGRAM</div><div class="caption-help">Texte officiel produit par Editorial Engine V2.</div><div class="copy-label">LÉGENDE</div><pre class="copy-box" id="captionText"></pre><div class="copy-actions"><button class="secondary" id="copyCaption">Copier la légende</button><button class="secondary" id="copyHashtags">Copier les hashtags</button></div><div class="copy-label">HASHTAGS</div><pre class="copy-box" id="hashtagsText"></pre><button class="primary copy-all" id="copyAll">Tout copier</button><div class="copy-status" id="copyStatus" aria-live="polite"></div></div></div><script>
const m=${safeJson(model)};
const storyCanvas=document.getElementById('story');const feedCanvas=document.getElementById('feed');const storyCtx=storyCanvas.getContext('2d');const feedCtx=feedCanvas.getContext('2d');let ctx=storyCtx;const INK='#12264A';const CANVAS_FONT='"Helvetica Neue",Arial,sans-serif';
function normalizeText(value){return String(value??'').normalize('NFC').replace(/\\s+/g,' ').trim();}
function load(src){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=reject;i.src=src;});}
function font(size,weight){ctx.font=String(weight)+' '+String(size)+'px '+CANVAS_FONT;if('fontKerning' in ctx)ctx.fontKerning='normal';}
function drawFullTextLine(label,x,y,color,align){ctx.fillStyle=color;ctx.strokeStyle=color;ctx.textAlign=align;ctx.textBaseline='alphabetic';ctx.lineJoin='round';ctx.miterLimit=2;ctx.lineWidth=.44;ctx.strokeText(label,x,y);ctx.fillText(label,x,y);}
function text(value,x,y,size,weight,color,align='left'){const label=normalizeText(value);ctx.save();font(size,weight);drawFullTextLine(label,x,y,color,align);ctx.restore();}
function trackedText(value,x,y,size,weight,color,tracking,align='center'){const chars=normalizeText(value).split('');ctx.save();font(size,weight);const widths=chars.map(ch=>ctx.measureText(ch).width);const total=widths.reduce((a,b)=>a+b,0)+Math.max(0,chars.length-1)*tracking;let cursor=align==='center'?x-total/2:align==='right'?x-total:x;ctx.fillStyle=color;ctx.textBaseline='alphabetic';for(let i=0;i<chars.length;i++){ctx.fillText(chars[i],cursor,y);cursor+=widths[i]+tracking;}ctx.restore();}
function fittedFontSize(value,maxWidth,maxSize,minSize,weight){const label=normalizeText(value);ctx.save();let size=maxSize;while(size>minSize){font(size,weight);if(ctx.measureText(label).width<=maxWidth)break;size-=1;}ctx.restore();return Math.max(minSize,size);}
function fittedText(value,x,y,maxWidth,maxSize,minSize,weight,color,align='left'){const size=fittedFontSize(value,maxWidth,maxSize,minSize,weight);text(value,x,y,size,weight,color,align);return size;}
function splitLines(value,maxWidth,maxLines,size,weight){const words=normalizeText(value).split(/\\s+/).filter(Boolean);ctx.save();font(size,weight);const lines=[];let line='';for(const word of words){const next=line?line+' '+word:word;if(line&&ctx.measureText(next).width>maxWidth){lines.push(line);line=word;if(lines.length>=maxLines){ctx.restore();return null;}}else line=next;}if(line)lines.push(line);ctx.restore();return lines.length<=maxLines?lines:null;}
function fitLines(value,maxWidth,maxLines,maxSize,minSize,weight){for(let size=maxSize;size>=minSize;size--){const lines=splitLines(value,maxWidth,maxLines,size,weight);if(lines)return{size,lines};}return{size:minSize,lines:[normalizeText(value)]};}
function wrap(value,x,y,maxWidth,lineHeight,size,weight,color,align='left',maxLines=2){ctx.save();font(size,weight);ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='alphabetic';const words=normalizeText(value).split(/\\s+/).filter(Boolean);let line='',yy=y,count=0;for(const word of words){const next=line?line+' '+word:word;if(ctx.measureText(next).width>maxWidth&&line){drawFullTextLine(line,x,yy,color,align);count++;if(count>=maxLines){ctx.restore();return;}line=word;yy+=lineHeight;}else line=next;}if(line&&count<maxLines)drawFullTextLine(line,x,yy,color,align);ctx.restore();}
function rr(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
function rgba(hex,a){const h=hex.replace('#','');const n=parseInt(h,16);return'rgba('+((n>>16)&255)+','+((n>>8)&255)+','+(n&255)+','+a+')';}
function dateLabel(date){try{return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',timeZone:m.timezone}).format(new Date(date+'T12:00:00')).toUpperCase();}catch{return String(date||'');}}
function drawCover(img,w,h){const iw=Math.max(1,img.naturalWidth||img.width||w);const ih=Math.max(1,img.naturalHeight||img.height||h);const scale=Math.max(w/iw,h/ih);const dw=iw*scale,dh=ih*scale;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);}
function box(x,y,w,h){ctx.save();rr(x,y,w,h,36);const g=ctx.createLinearGradient(x,y,x,y+h);g.addColorStop(0,'rgba(255,255,255,0.15)');g.addColorStop(.48,'rgba(255,255,255,0.12)');g.addColorStop(1,'rgba(255,255,255,0.095)');ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='rgba(255,255,255,0.82)';ctx.lineWidth=1.45;ctx.stroke();ctx.save();rr(x+2,y+2,w-4,(h-4)*.43,34);ctx.clip();const sheen=ctx.createLinearGradient(x,y,x,y+h*.48);sheen.addColorStop(0,'rgba(255,255,255,0.16)');sheen.addColorStop(1,'rgba(255,255,255,0.018)');ctx.fillStyle=sheen;ctx.fillRect(x+2,y+2,w-4,h*.48);ctx.restore();ctx.restore();}
function separator(x1,y1,x2,y2){ctx.save();ctx.strokeStyle='rgba(18,38,74,0.13)';ctx.lineWidth=1.05;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.restore();}
function iconStrokePx(size){return size>=128?4.15:3.65;}
function iconContext(x,y,size,color){const scale=size/100;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=iconStrokePx(size)/scale;ctx.lineCap='round';ctx.lineJoin='round';return scale;}
function drawCloud(x,y,size,color){iconContext(x,y,size,color);ctx.beginPath();ctx.moveTo(-48,22);ctx.bezierCurveTo(-55,16,-55,5,-49,-3);ctx.bezierCurveTo(-44,-10,-36,-13,-28,-11);ctx.bezierCurveTo(-24,-31,-10,-45,8,-45);ctx.bezierCurveTo(25,-45,38,-33,40,-17);ctx.bezierCurveTo(47,-21,56,-19,62,-13);ctx.bezierCurveTo(70,-5,69,8,63,16);ctx.bezierCurveTo(58,23,51,27,41,27);ctx.lineTo(-38,27);ctx.bezierCurveTo(-43,27,-47,25,-48,22);ctx.stroke();ctx.restore();}
function drawSun(x,y,size,color){iconContext(x,y,size,color);ctx.beginPath();ctx.arc(0,0,19,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(Math.cos(a)*31,Math.sin(a)*31);ctx.lineTo(Math.cos(a)*44,Math.sin(a)*44);ctx.stroke();}ctx.restore();}
function drawPartly(x,y,size,color){const s=size/100;drawSun(x+22*s,y-19*s,size*.72,color);drawCloud(x-9*s,y+12*s,size*.84,color);}
function drawRain(x,y,size,color,drizzle=false){const s=size/100;drawCloud(x,y-14*s,size*.86,color);ctx.save();ctx.strokeStyle=color;ctx.lineWidth=iconStrokePx(size);ctx.lineCap='round';const drops=drizzle?[-19,0,19]:[-27,-9,9,27];drops.forEach((dx,index)=>{const y0=y+(drizzle?24:22)*s+(index%2)*2*s;ctx.beginPath();ctx.moveTo(x+dx*s,y0);ctx.lineTo(x+(dx-5)*s,y0+(drizzle?12:20)*s);ctx.stroke();});ctx.restore();}
function drawThunder(x,y,size,color){const s=size/100;drawCloud(x,y-15*s,size*.86,color);ctx.save();ctx.strokeStyle=color;ctx.lineWidth=iconStrokePx(size)+.2;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x+4*s,y+5*s);ctx.lineTo(x-10*s,y+29*s);ctx.lineTo(x+1*s,y+28*s);ctx.lineTo(x-6*s,y+50*s);ctx.lineTo(x+18*s,y+17*s);ctx.lineTo(x+8*s,y+18*s);ctx.stroke();ctx.restore();}
function drawWind(x,y,size,color){iconContext(x,y,size,color);ctx.beginPath();ctx.moveTo(-48,-20);ctx.lineTo(25,-20);ctx.bezierCurveTo(42,-20,43,-39,29,-39);ctx.bezierCurveTo(19,-39,15,-32,16,-27);ctx.stroke();ctx.beginPath();ctx.moveTo(-48,0);ctx.lineTo(39,0);ctx.bezierCurveTo(55,0,56,20,40,20);ctx.bezierCurveTo(30,20,26,13,27,8);ctx.stroke();ctx.beginPath();ctx.moveTo(-32,20);ctx.lineTo(10,20);ctx.bezierCurveTo(25,20,25,39,11,39);ctx.bezierCurveTo(2,39,-2,33,-2,28);ctx.stroke();ctx.restore();}
function drawFog(x,y,size,color){iconContext(x,y,size,color);const rows=[[-44,-22,-9,-22,7,-22,39,-22],[-33,-7,8,-7,22,-7,47,-7],[-47,8,-16,8,-2,8,34,8],[-34,23,1,23,16,23,40,23]];for(const r of rows){ctx.beginPath();ctx.moveTo(r[0],r[1]);ctx.lineTo(r[2],r[3]);ctx.moveTo(r[4],r[5]);ctx.lineTo(r[6],r[7]);ctx.stroke();}ctx.restore();}
function drawCloudWind(x,y,size,color){const s=size/100;drawCloud(x-7*s,y-17*s,size*.78,color);drawWind(x+12*s,y+29*s,size*.60,color);}
function drawSunWind(x,y,size,color){const s=size/100;drawSun(x-18*s,y-20*s,size*.66,color);drawWind(x+15*s,y+25*s,size*.62,color);}
function drawRainWind(x,y,size,color){const s=size/100;drawCloud(x-10*s,y-20*s,size*.72,color);ctx.save();ctx.strokeStyle=color;ctx.lineWidth=iconStrokePx(size);ctx.lineCap='round';[-23,-7,9].forEach((dx,index)=>{const y0=y+(10+index*2)*s;ctx.beginPath();ctx.moveTo(x+dx*s,y0);ctx.lineTo(x+(dx-5)*s,y0+18*s);ctx.stroke();});ctx.restore();drawWind(x+20*s,y+31*s,size*.48,color);}
function primitiveIcon(kind){if(kind==='veil'||kind==='mixed')return'partly';if(kind==='shower')return'rain';return kind;}
function drawWeatherIcon(kind,x,y,size,color){const k=primitiveIcon(kind);if(k==='sun')return drawSun(x,y,size,color);if(k==='partly')return drawPartly(x,y,size,color);if(k==='rain')return drawRain(x,y,size,color,false);if(k==='thunder')return drawThunder(x,y,size,color);if(k==='wind')return drawWind(x,y,size,color);if(k==='fog')return drawFog(x,y,size,color);if(k==='cloud-wind')return drawCloudWind(x,y,size,color);if(k==='rain-wind')return drawRainWind(x,y,size,color);if(k==='sun-wind')return drawSunWind(x,y,size,color);return drawCloud(x,y,size,color);}
function hourlyIcon(condition){if(condition==='soleil')return'sun';if(condition==='peu nuageux'||condition==='variable')return'partly';if(condition==='nuageux'||condition==='couvert')return'cloud';if(condition==='brouillard')return'fog';if(condition==='vent')return'wind';if(condition==='averse'||condition==='pluie')return'rain';if(condition==='orage')return'thunder';return'cloud';}
function drawHourlyWeatherIcon(kind,x,y,color){const size=kind==='fog'?114:kind==='wind'?112:kind==='sun'?112:kind==='partly'?112:kind==='cloud'?110:108;drawWeatherIcon(kind,x,y,size,color);}
function drawFeedHourlyWeatherIcon(kind,x,y,color){const size=kind==='fog'?92:kind==='wind'?90:kind==='sun'?90:kind==='partly'?90:kind==='cloud'?88:87;drawWeatherIcon(kind,x,y,size,color);}
function drawSolarIcon(kind,x,y,scale,color){if(kind==='noon'){drawSun(x,y-1,76*scale,color);return;}ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);ctx.strokeStyle=color;ctx.lineWidth=2.65/scale;ctx.lineCap='round';ctx.lineJoin='round';function line(x1,y1,x2,y2){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}const isDawn=kind==='dawn',isRise=kind==='sunrise',isSet=kind==='sunset',isDusk=kind==='dusk';const cy=isDawn?13:isDusk?15:11;const r=isDawn?14:isDusk?13:15;const horizonY=19;ctx.beginPath();ctx.arc(0,cy,r,Math.PI,0);ctx.stroke();line(-31,horizonY,31,horizonY);if(isRise){line(-25,27,25,27);line(-17,34,17,34);}else if(isSet){line(-24,27,24,27);line(-13,34,13,34);}else if(isDusk){line(-22,27,22,27);}const rays=isDawn?[[0,-18,0,-28],[-19,-10,-25,-17],[19,-10,25,-17]]:isDusk?[[0,-16,0,-24],[-18,-8,-23,-13],[18,-8,23,-13]]:[[0,-18,0,-29],[-20,-11,-27,-18],[20,-11,27,-18],[-31,1,-39,-2],[31,1,39,-2]];for(const ray of rays)line(ray[0],ray[1],ray[2],ray[3]);ctx.restore();}
function pickHourlySlots(source){const wanted=[4,6,8,10,12,14,16,18,20,22];const pool=Array.isArray(source)?source:[];return wanted.map(hour=>pool.find(item=>Number(item.hour)===hour)||{hour,temperatureC:'—',condition:'nuageux',missing:true});}
function solarShiftLabel(value){if(value===null||value===undefined||value==='')return'';const delta=Number(value);if(!Number.isFinite(delta))return'';const rounded=Math.round(delta);if(rounded===0)return'0 min';return(rounded>0?'+':'−')+String(Math.abs(rounded))+' min';}
function drawHeader(){text('LOKA!',50,132,66,400,INK);trackedText(String(m.city||'Tarnos').toUpperCase(),540,122,25,680,INK,8,'center');text(dateLabel(m.date),1030,122,22,540,INK,'right');}
function drawFeedHeader(){text('LOKA!',50,100,60,400,INK);trackedText(String(m.city||'Tarnos').toUpperCase(),540,94,22,680,INK,8,'center');text(dateLabel(m.date),1030,94,19,540,INK,'right');}
function drawTitleBlock(title,x,oneLineY,twoLineY,maxWidth,maxSize,minSize,weight,color){const oneSize=fittedFontSize(title,maxWidth,maxSize,minSize,weight);ctx.save();font(maxSize,weight);const fitsOne=ctx.measureText(normalizeText(title)).width<=maxWidth;ctx.restore();if(fitsOne){text(title,x,oneLineY,maxSize,weight,color);return{lines:1,size:maxSize,bottom:oneLineY};}const fit=fitLines(title,maxWidth,2,Math.min(maxSize,52),minSize,weight);const lineHeight=Math.round(fit.size*.98);fit.lines.forEach((line,i)=>text(line,x,twoLineY+i*lineHeight,fit.size,weight,color));return{lines:fit.lines.length,size:fit.size,bottom:twoLineY+(fit.lines.length-1)*lineHeight};}
function drawSubtitleBlock(value,x,oneLineY,twoLineY,maxWidth,maxSize,minSize,color){ctx.save();font(maxSize,550);const fitsOne=ctx.measureText(normalizeText(value)).width<=maxWidth;ctx.restore();if(fitsOne){text(value,x,oneLineY,maxSize,550,color);return{lines:1,size:maxSize};}const fit=fitLines(value,maxWidth,2,Math.min(maxSize,23),minSize,550);const lineHeight=Math.round(fit.size*1.16);fit.lines.forEach((line,i)=>text(line,x,twoLineY+i*lineHeight,fit.size,550,color));return{lines:fit.lines.length,size:fit.size};}
function drawGeneralBox(){const x=44,y=224,w=992,h=250;box(x,y,w,h);const iconX=172,iconY=324,iconSize=142,titleX=302,titleMaxWidth=455;drawWeatherIcon(m.scene.visualIcon,iconX,iconY,iconSize,INK);const titleInfo=drawTitleBlock(m.scene.title,titleX,330,296,titleMaxWidth,66,34,800,INK);const subtitleInfo=drawSubtitleBlock(m.visual.subtitle,titleX,418,394,455,27,19,rgba(INK,.99));text(String(m.temps.minC)+'° — '+String(m.temps.maxC)+'°',976,354,49,600,INK,'right');window.__LOKA_GENERAL_BOX_AUDIT={titleLines:titleInfo.lines,titleSize:titleInfo.size,subtitleLines:subtitleInfo.lines,subtitleSize:subtitleInfo.size,layout:'REFERENCE_GLASS'};}
function drawFeedGeneralBox(){const x=50,y=160,w=980,h=240;box(x,y,w,h);const iconX=170,iconY=272,iconSize=132,titleX=290,titleMaxWidth=470;drawWeatherIcon(m.scene.visualIcon,iconX,iconY,iconSize,INK);const titleInfo=drawTitleBlock(m.scene.title,titleX,286,255,titleMaxWidth,60,32,800,INK);drawSubtitleBlock(m.visual.subtitle,titleX,350,332,470,23,17,rgba(INK,.99));text(String(m.temps.minC)+'° — '+String(m.temps.maxC)+'°',980,305,46,600,INK,'right');}
function drawHourlyBox(items){const x=44,y=520,w=992,h=704;box(x,y,w,h);const colW=w/5;const rowTop=[548,894],rowBottom=[872,1198];separator(x+20,886,x+w-20,886);for(let row=0;row<2;row++){for(let i=1;i<5;i++)separator(x+colW*i,rowTop[row]+18,x+colW*i,rowBottom[row]-18);for(let c=0;c<5;c++){const item=items[row*5+c];const cx=x+colW*(c+.5),base=rowTop[row];text(String(item.hour).padStart(2,'0')+'h',cx,base+52,26,600,INK,'center');if(!item.missing)drawHourlyWeatherIcon(hourlyIcon(item.condition),cx,base+137,INK);text(String(item.temperatureC)+(item.missing?'':'°'),cx,base+242,43,700,INK,'center');}}}
function drawFeedHourlyBox(items){const x=50,y=426,w=980,h=500;box(x,y,w,h);const colW=w/5;const rowTop=[446,690],rowBottom=[666,910];separator(x+20,678,x+w-20,678);for(let row=0;row<2;row++){for(let i=1;i<5;i++)separator(x+colW*i,rowTop[row]+10,x+colW*i,rowBottom[row]-10);for(let c=0;c<5;c++){const item=items[row*5+c];const cx=x+colW*(c+.5),base=rowTop[row];text(String(item.hour).padStart(2,'0')+'h',cx,base+32,22,600,INK,'center');if(!item.missing)drawFeedHourlyWeatherIcon(hourlyIcon(item.condition),cx,base+92,INK);text(String(item.temperatureC)+(item.missing?'':'°'),cx,base+186,36,700,INK,'center');}}}
function drawCommentBox(){const x=44,y=1263,w=992,h=172;box(x,y,w,h);const main=normalizeText(m.visual.primaryLine),secondary=normalizeText(m.visual.secondaryLine);const mainSize=fittedFontSize(main,910,34,28,600);ctx.save();font(mainSize,600);const mainWidth=ctx.measureText(main).width;ctx.restore();if(mainWidth<=910)text(main,540,1345,mainSize,600,INK,'center');else wrap(main,540,1329,910,36,27,600,INK,'center',2);if(secondary){const secondarySize=fittedFontSize(secondary,900,26,23,600);ctx.save();font(secondarySize,600);const secondaryWidth=ctx.measureText(secondary).width;ctx.restore();if(secondaryWidth<=900)text(secondary,540,1401,secondarySize,600,rgba(INK,.99),'center');else wrap(secondary,540,1389,900,31,23,600,rgba(INK,.99),'center',2);}}
function drawFeedCommentBox(){const x=50,y=955,w=980,h=120;box(x,y,w,h);const main=normalizeText(m.visual.primaryLine),secondary=normalizeText(m.visual.secondaryLine);const mainSize=fittedFontSize(main,900,29,25,600);ctx.save();font(mainSize,600);const mainWidth=ctx.measureText(main).width;ctx.restore();if(mainWidth<=900)text(main,540,1003,mainSize,600,INK,'center');else wrap(main,540,994,900,29,24,600,INK,'center',2);if(secondary){const secondarySize=fittedFontSize(secondary,890,21,19,550);ctx.save();font(secondarySize,550);const secondaryWidth=ctx.measureText(secondary).width;ctx.restore();if(secondaryWidth<=890)text(secondary,540,1042,secondarySize,550,rgba(INK,.99),'center');else wrap(secondary,540,1035,890,25,19,550,rgba(INK,.99),'center',2);}}
function drawSolarBox(){const s=m.solar,x=44,y=1479,w=992,h=279;box(x,y,w,h);const colW=w/5;for(let i=1;i<5;i++)separator(x+colW*i,y+28,x+colW*i,y+h-28);const defs=[['AUBE','dawn',s.dawn,null],['LEVER','sunrise',s.sunrise,s.sunriseDeltaMinutes],['MIDI SOLAIRE','noon',s.solarNoon,null],['COUCHER','sunset',s.sunset,s.sunsetDeltaMinutes],['CRÉPUSCULE','dusk',s.dusk,null]];defs.forEach((d,i)=>{const cx=x+colW*(i+.5);text(d[0],cx,1547,18,700,INK,'center');drawSolarIcon(d[1],cx,1635,1,INK);text(d[2]||'—',cx,1716,33,600,INK,'center');const shift=solarShiftLabel(d[3]);if(shift)text(shift,cx,1748,19,600,rgba(INK,.88),'center');});}
function drawFeedSolarBox(){const s=m.solar,x=50,y=1100,w=980,h=205;box(x,y,w,h);const colW=w/5;for(let i=1;i<5;i++)separator(x+colW*i,y+18,x+colW*i,y+h-18);const defs=[['AUBE','dawn',s.dawn,null],['LEVER','sunrise',s.sunrise,s.sunriseDeltaMinutes],['MIDI SOLAIRE','noon',s.solarNoon,null],['COUCHER','sunset',s.sunset,s.sunsetDeltaMinutes],['CRÉPUSCULE','dusk',s.dusk,null]];defs.forEach((d,i)=>{const cx=x+colW*(i+.5);text(d[0],cx,1138,15,700,INK,'center');drawSolarIcon(d[1],cx,1192,.78,INK);text(d[2]||'—',cx,1252,28,600,INK,'center');const shift=solarShiftLabel(d[3]);if(shift)text(shift,cx,1280,16,600,rgba(INK,.84),'center');});}
function drawSignature(){text('Ici, aujourd’hui.',540,1834,22,500,INK,'center');ctx.save();ctx.strokeStyle=rgba(INK,.72);ctx.lineWidth=1.2;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(514,1858);ctx.lineTo(566,1858);ctx.stroke();ctx.restore();}
function drawFeedSignature(){text('Ici, aujourd’hui.',540,1368,18,500,rgba(INK,.88),'center');ctx.save();ctx.strokeStyle=rgba(INK,.60);ctx.lineWidth=1;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(518,1387);ctx.lineTo(562,1387);ctx.stroke();ctx.restore();}
function renderStory(bg,slots){ctx=storyCtx;ctx.clearRect(0,0,1080,1920);drawCover(bg,1080,1920);drawHeader();drawGeneralBox();drawHourlyBox(slots);drawCommentBox();drawSolarBox();drawSignature();}
function renderFeed(bg,slots){ctx=feedCtx;ctx.clearRect(0,0,1080,1440);drawCover(bg,1080,1440);drawFeedHeader();drawFeedGeneralBox();drawFeedHourlyBox(slots);drawFeedCommentBox();drawFeedSolarBox();drawFeedSignature();ctx=storyCtx;}
function pngFile(targetCanvas,suffix){const b=atob(targetCanvas.toDataURL('image/png').split(',')[1]);const u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return new File([u],'LOKA_'+String(m.date||'meteo')+'_'+suffix+'.png',{type:'image/png'});}
function fallbackDownload(file){const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=file.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function shareCanvas(targetCanvas,suffix){const file=pngFile(targetCanvas,suffix);if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){navigator.share({files:[file],title:'LOKA!'}).catch(error=>{if(error?.name!=='AbortError')fallbackDownload(file);});return;}fallbackDownload(file);}
function fallbackCopy(value){const area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();area.setSelectionRange(0,area.value.length);let ok=false;try{ok=document.execCommand('copy');}catch{}area.remove();return ok;}
async function copyText(value,label){let ok=false;try{if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(value);ok=true;}}catch{}if(!ok)ok=fallbackCopy(value);const status=document.getElementById('copyStatus');status.textContent=ok?label+' copié.':'Copie impossible : sélectionne le texte manuellement.';}
document.getElementById('captionText').textContent=m.social.caption;document.getElementById('hashtagsText').textContent=m.social.hashtags;document.getElementById('copyCaption').onclick=()=>copyText(m.social.caption,'Légende');document.getElementById('copyHashtags').onclick=()=>copyText(m.social.hashtags,'Hashtags');document.getElementById('copyAll').onclick=()=>copyText(m.social.caption+'\\n\\n'+m.social.hashtags,'Légende + hashtags');document.getElementById('shareStory').onclick=()=>shareCanvas(storyCanvas,'STORY');document.getElementById('shareFeed').onclick=()=>shareCanvas(feedCanvas,'FEED');
(async()=>{window.__LOKA_RENDER_STATUS={version:'V2_REFERENCE_GLASS',started:true,storyRendered:false,feedRendered:false,rendererReclassified:false,error:null};try{const bg=await load(m.masterUrl);const slots=pickHourlySlots(m.hourly);renderStory(bg,slots);window.__LOKA_RENDER_STATUS.storyRendered=true;renderFeed(bg,slots);window.__LOKA_RENDER_STATUS.feedRendered=true;window.__LOKA_RENDER_STATUS.rendered=true;window.__LOKA_EDITORIAL_AUDIT={sceneId:m.scene.id,title:m.scene.title,subtitle:m.visual.subtitle,primary:m.visual.primaryLine,secondary:m.visual.secondaryLine,rendererReclassified:false};}catch(error){window.__LOKA_RENDER_STATUS.error=String(error);document.getElementById('summary').textContent='Erreur de rendu : '+String(error);}})();
</script></body></html>`;
}
