const EDITOR_STYLE = `<style>
.editor-card{background:#fff;border-radius:24px;padding:18px;margin:4px 0 18px;box-shadow:0 10px 34px rgba(0,0,0,.05)}.editor-top{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.editor-title{font-size:14px;font-weight:760;letter-spacing:.08em}.editor-badge{font-size:10px;letter-spacing:.06em;text-transform:uppercase;color:#8a6100;background:#fff6d8;padding:6px 8px;border-radius:999px;white-space:nowrap}.editor-help{font-size:11px;line-height:1.45;color:var(--muted);margin:5px 0 14px}.editor-format{border:1px solid #eceae4;border-radius:18px;padding:14px;margin-top:11px}.editor-format-title{font-size:12px;font-weight:760;letter-spacing:.09em;margin-bottom:5px}.editor-format-help{font-size:10px;line-height:1.45;color:#8d8983;margin-bottom:8px}.editor-field{display:block;margin-top:10px}.editor-field span{display:block;font-size:10px;font-weight:720;letter-spacing:.07em;color:#625f58;margin:0 0 6px;text-transform:uppercase}.editor-field input,.editor-field textarea{display:block;width:100%;border:1px solid #dedbd3;border-radius:12px;background:#fbfaf7;color:#171715;padding:11px 12px;font:500 14px/1.45 -apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;resize:vertical;outline:none}.editor-field input:focus,.editor-field textarea:focus{border-color:#b18a2f;box-shadow:0 0 0 3px rgba(253,181,21,.12)}.editor-copy{width:100%;margin-top:9px}.editor-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.editor-actions button{width:100%;margin:0}.editor-status{min-height:20px;padding-top:9px;text-align:center;font-size:11px;color:#24653a}.editor-warning{font-size:10px;line-height:1.45;color:#8a6100;background:#fff8e2;border-radius:12px;padding:9px 10px;margin-top:12px}@media(max-width:420px){.editor-top{display:block}.editor-badge{display:inline-block;margin-top:7px}.editor-actions{grid-template-columns:1fr}}
</style>`;

const EDITOR_MARKUP = `<div class="editor-card" id="editorialStudio"><div class="editor-top"><div><div class="editor-title">ÉDITION DES TEXTES</div><div class="editor-help">Un seul jeu de textes pilote désormais la Story et la Publication. Le titre de scène, les pictogrammes, les températures, les horaires météo et les informations solaires restent verrouillés.</div></div><div class="editor-badge">Editorial Studio · V1.4</div></div><div class="editor-format"><div class="editor-format-title">COMMENTAIRE MÉTÉO</div><div class="editor-format-help">Ces deux lignes sont utilisées à l’identique sur la Story météo et la Publication.</div><label class="editor-field"><span>Commentaire principal</span><textarea id="sharedPrimary" rows="2" maxlength="500"></textarea></label><label class="editor-field"><span>Commentaire secondaire</span><textarea id="sharedSecondary" rows="3" maxlength="500"></textarea></label></div><div class="editor-format"><div class="editor-format-title">LÉGENDE DU JOUR</div><div class="editor-format-help">Cette légende est dessinée dans la nouvelle Story dédiée et sert également de texte à la publication Instagram. La signature et le compte LOKA! sont ajoutés automatiquement à la publication.</div><label class="editor-field"><span>Légende</span><textarea id="sharedLegend" rows="8" maxlength="8000"></textarea></label><button class="secondary editor-copy" id="copySharedLegend" type="button">Copier la légende</button></div><div class="editor-format"><div class="editor-format-title">HASHTAGS</div><div class="editor-format-help">Un seul bloc de hashtags pour la publication. Ils ne sont pas dessinés dans la Story légende.</div><label class="editor-field"><span>Hashtags</span><textarea id="sharedHashtags" rows="3" maxlength="3000"></textarea></label><button class="secondary editor-copy" id="copySharedHashtags" type="button">Copier les hashtags</button><button class="secondary editor-copy" id="copySharedPublication" type="button">Copier la publication complète</button></div><div class="editor-actions"><button class="primary" id="applyEditorial" type="button">Appliquer aux visuels</button><button class="secondary" id="resetEditorial" type="button">Rétablir l’officiel</button></div><div class="editor-warning">Story météo, Story légende et Publication restent liées à la même scène officielle. Les sondages et champs d’interaction ne sont plus proposés.</div><div class="editor-status" id="editorStatus" aria-live="polite"></div></div>`;

const EDITOR_SCRIPT = `<script>
(function(){
const officialVisual={...m.visual};const officialSocial={...m.social};const officialEngagement={format:m.engagement?.format==='POLL'?'POLL':'QUESTION',question:String(m.engagement?.question||''),options:Array.isArray(m.engagement?.options)?[String(m.engagement.options[0]||''),String(m.engagement.options[1]||'')]:null};
const clean=value=>String(value??'').replace(/\\r\\n?/g,'\\n').normalize('NFC').trim();
const legacySubtitle={story:clean(officialVisual.subtitle),feed:clean(officialVisual.subtitle)};
function resetLegacySubtitles(){legacySubtitle.story=clean(officialVisual.subtitle);legacySubtitle.feed=clean(officialVisual.subtitle);}
window.__LOKA_EDITORIAL_LEGACY_SUBTITLE={version:'1.0',get:format=>format==='feed'?legacySubtitle.feed:legacySubtitle.story,set:(format,value)=>{if(format==='feed')legacySubtitle.feed=clean(value);else legacySubtitle.story=clean(value);},reset:resetLegacySubtitles};
const byId=id=>document.getElementById(id);const value=id=>clean(byId(id)?.value);
function legendFromSocial(social){return[clean(social?.paragraph1),clean(social?.paragraph2)].filter(Boolean).join('\\n\\n');}
function publicationCaption(legend){const blocks=[];if(clean(legend))blocks.push(clean(legend));let signature='';if(officialSocial.signature)signature+=officialSocial.signature;if(officialSocial.handle)signature+=(signature?'\\n':'')+officialSocial.handle;if(signature)blocks.push(signature);return blocks.join('\\n\\n');}
function publicationFromFields(){const caption=publicationCaption(value('sharedLegend')),hashtags=value('sharedHashtags');return caption+(hashtags?(caption?'\\n\\n':'')+hashtags:'');}
const officialLegend=legendFromSocial(officialSocial);
m.storyVisual={...officialVisual,subtitle:legacySubtitle.story};m.feedVisual={...officialVisual,subtitle:legacySubtitle.feed};m.storySocial={...officialSocial};m.feedSocial={...officialSocial};m.legendText=officialLegend;m.engagement={...officialEngagement,options:officialEngagement.options?[...officialEngagement.options]:null};
function writeOfficial(){resetLegacySubtitles();byId('sharedPrimary').value=officialVisual.primaryLine||'';byId('sharedSecondary').value=officialVisual.secondaryLine||'';byId('sharedLegend').value=officialLegend;byId('sharedHashtags').value=officialSocial.hashtags||'';}
let assetsPromise=null;function assets(){if(!assetsPromise){assetsPromise=(async()=>{const slots=pickHourlySlots(m.hourly);const bg=await load(m.masterUrl,'editor_background');const logo=await load(m.brand.logoUrl,'editor_logo');const mainIcon=await load(m.scene.pictogramUrl,'editor_main_pictogram');const hourIcons=await Promise.all(slots.map((item,index)=>load(item.pictogramUrl,'editor_hourly_pictogram_'+index)));const solarIcons={dawn:await load(m.solarPictograms.dawn,'editor_solar_dawn'),sunrise:await load(m.solarPictograms.sunrise,'editor_solar_sunrise'),noon:await load(m.solarPictograms.noon,'editor_solar_noon'),sunset:await load(m.solarPictograms.sunset,'editor_solar_sunset'),dusk:await load(m.solarPictograms.dusk,'editor_solar_dusk')};return{slots,bg,logo,mainIcon,hourIcons,solarIcons};})();}return assetsPromise;}
function updateCopyArea(){const caption=publicationCaption(m.legendText),hashtags=m.feedSocial.hashtags||'';m.feedSocial.caption=caption;byId('captionText').textContent=caption;byId('hashtagsText').textContent=hashtags;const help=document.querySelector('.caption-help');if(help)help.textContent='Même légende que la Story dédiée, avec signature LOKA! ajoutée automatiquement.';byId('copyCaption').onclick=()=>copyText(caption,'Légende');byId('copyHashtags').onclick=()=>copyText(hashtags,'Hashtags');byId('copyAll').onclick=()=>copyText(caption+(hashtags?'\\n\\n'+hashtags:''),'Légende + hashtags');}
async function applyDrafts(showStatus=true){const primary=value('sharedPrimary'),secondary=value('sharedSecondary'),legend=value('sharedLegend'),hashtags=value('sharedHashtags');m.storyVisual={...officialVisual,subtitle:legacySubtitle.story,primaryLine:primary,secondaryLine:secondary};m.feedVisual={...officialVisual,subtitle:legacySubtitle.feed,primaryLine:primary,secondaryLine:secondary};m.legendText=legend;m.storySocial={...officialSocial,hashtags};m.feedSocial={...officialSocial,paragraph1:legend,paragraph2:'',caption:publicationCaption(legend),hashtags};const a=await assets();renderStory(a.bg,a.logo,a.mainIcon,a.slots,a.hourIcons,a.solarIcons);renderLegendStory(a.bg,a.logo);renderFeed(a.bg,a.logo,a.mainIcon,a.slots,a.hourIcons,a.solarIcons);updateCopyArea();window.__LOKA_EDITORIAL_DRAFT={story:{visual:{...m.storyVisual},hashtags,engagement:{...m.engagement,options:m.engagement.options?[...m.engagement.options]:null}},feed:{visual:{...m.feedVisual},paragraph1:legend,paragraph2:'',caption:m.feedSocial.caption,hashtags},shared:{legend,hashtags,primaryLine:primary,secondaryLine:secondary},persisted:false};if(showStatus){byId('editorStatus').textContent='Story et Publication actualisées.';setTimeout(()=>{if(byId('editorStatus').textContent==='Story et Publication actualisées.')byId('editorStatus').textContent='';},1800);}}
let timer=null;function schedule(){clearTimeout(timer);timer=setTimeout(()=>applyDrafts(false).catch(error=>{byId('editorStatus').textContent='Erreur de rendu : '+String(error);}),220);}
['sharedPrimary','sharedSecondary','sharedLegend','sharedHashtags'].forEach(id=>{byId(id).addEventListener('input',schedule);});
byId('applyEditorial').onclick=()=>applyDrafts(true).catch(error=>{byId('editorStatus').textContent='Erreur de rendu : '+String(error);});
byId('resetEditorial').onclick=()=>{writeOfficial();m.storyVisual={...officialVisual};m.feedVisual={...officialVisual};m.legendText=officialLegend;m.storySocial={...officialSocial};m.feedSocial={...officialSocial};applyDrafts(false).then(()=>{byId('editorStatus').textContent='Version officielle rétablie.';setTimeout(()=>{if(byId('editorStatus').textContent==='Version officielle rétablie.')byId('editorStatus').textContent='';},1800);}).catch(error=>{byId('editorStatus').textContent='Erreur de rendu : '+String(error);});};
byId('copySharedLegend').onclick=()=>copyText(value('sharedLegend'),'Légende');byId('copySharedHashtags').onclick=()=>copyText(value('sharedHashtags'),'Hashtags');byId('copySharedPublication').onclick=()=>copyText(publicationFromFields(),'Publication complète');
writeOfficial();updateCopyArea();window.__LOKA_EDITORIAL_STUDIO={version:'1.4',persistence:'EDITORIAL_FEEDBACK',activeVisualFields:['primaryLine','secondaryLine'],activeSharedFields:['legend','hashtags'],engagementUi:'DISABLED',legacySubtitle:'HIDDEN_COMPATIBILITY',officialVisual:{...officialVisual},officialSocial:{...officialSocial},officialEngagement:{...officialEngagement}};
})();
</script>`;

function replaceRequired(source: string, before: string, after: string, label: string): string {
  if (!source.includes(before)) throw new Error(`instagram_editorial_studio_marker_missing_${label}`);
  return source.replace(before, after);
}

export function enhanceInstagramWithEditorialStudio(html: string): string {
  let result = html;

  result = replaceRequired(result, "<!--LOKA_EDITORIAL_STYLE_MOUNT-->", EDITOR_STYLE, "style_mount");
  result = replaceRequired(result, "<!--LOKA_EDITORIAL_STUDIO_MOUNT-->", EDITOR_MARKUP, "studio_mount");
  result = replaceRequired(result, "<!--LOKA_EDITORIAL_SCRIPT_MOUNT-->", EDITOR_SCRIPT, "script_mount");

  return result;
}
