import type { V24OfficialPublicPayload } from "../engine/publicProduct";

export function renderInstagramOfficial24(
  p: V24OfficialPublicPayload,
  timezone: string
): string {
  const payload = JSON.stringify(p).replace(/</g, "\\u003c");
  const cfg = JSON.stringify({ timezone }).replace(/</g, "\\u003c");

  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>LOKA! — Studio Instagram V24</title><style>
*{box-sizing:border-box}body{margin:0;background:#ecebe7;color:#17212b;font-family:-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;padding:16px 12px 28px}.wrap{width:min(100%,580px);margin:auto}.toolbar{background:#fff;border-radius:24px;padding:18px;margin-bottom:14px}.badge{display:inline-block;padding:6px 9px;border-radius:999px;background:#e8f3ea;color:#24653a;font-size:11px;font-weight:750}h1{font-size:22px;margin:10px 0 5px}.muted{font-size:12px;line-height:1.5;color:#71767a}.actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}button,a{border:0;border-radius:14px;padding:14px 10px;text-decoration:none;text-align:center;font:650 13px/1 -apple-system,BlinkMacSystemFont,sans-serif}.primary{background:#171715;color:#fff}.secondary{background:#f1f1ee;color:#171715}.canvas-wrap{background:#ddd;border-radius:26px;overflow:hidden;box-shadow:0 18px 70px rgba(0,0,0,.14)}canvas{display:block;width:100%;height:auto}.debug{margin-top:12px;background:#fff;border-radius:18px;padding:14px;font-size:12px;line-height:1.55;color:#555}
</style></head><body><div class="wrap"><div class="toolbar"><div class="badge">STUDIO OFFICIEL · V24</div><h1>Visuel Instagram LOKA!</h1><div class="muted">Ce Studio suit exactement la génération publique V24 effective. Si une génération retombe sur Legacy, /instagram utilisera automatiquement le Studio Legacy.</div><div class="actions"><button class="primary" id="share">Partager / enregistrer</button><a class="secondary" href="/">Voir la météo</a></div><div class="actions"><a class="secondary" href="/admin">Admin</a><a class="secondary" href="/instagram24">QA Shadow V24</a></div></div><div class="canvas-wrap"><canvas id="post" width="1080" height="1350"></canvas></div><div class="debug" id="debug"></div></div><script>
const p=${payload},cfg=${cfg};const canvas=document.getElementById("post"),ctx=canvas.getContext("2d");
function load(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
function font(s,w){ctx.font=String(w)+" "+String(s)+'px -apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif'}
function text(t,x,y,s,w,c,a="left"){ctx.save();font(s,w);ctx.fillStyle=c;ctx.textAlign=a;ctx.fillText(String(t),x,y);ctx.restore()}
function wrap(t,x,y,mw,lh,s,w,c,a="left",max=2){ctx.save();font(s,w);ctx.fillStyle=c;ctx.textAlign=a;let line="",yy=y,n=0;for(const word of String(t||"").split(/\\s+/)){const q=line?line+" "+word:word;if(ctx.measureText(q).width>mw&&line){ctx.fillText(line,x,yy);n++;if(n>=max){ctx.restore();return}line=word;yy+=lh}else line=q}if(line&&n<max)ctx.fillText(line,x,yy);ctx.restore()}
function rr(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function dateLabel(d){try{return new Intl.DateTimeFormat("fr-FR",{day:"2-digit",month:"short",year:"numeric",timeZone:cfg.timezone}).format(new Date(d+"T12:00:00")).replace(".","").toUpperCase()}catch{return d}}
function icon(c){c=String(c||"").toLowerCase();if(c.includes("orage"))return"ϟ";if(c.includes("pluie")||c.includes("averse"))return"☂";if(c.includes("soleil"))return"☀";if(c.includes("vent"))return"≋";return"☁"}
async function draw(){const s=p.scene,img=await load(s.masterUrl),dark=[10,12,13,20,22,24].includes(s.id),ink=dark?"#fff":"#17212b";ctx.clearRect(0,0,1080,1350);ctx.drawImage(img,0,0,1080,1350);const sh=ctx.createLinearGradient(0,0,0,470);sh.addColorStop(0,dark?"rgba(0,0,0,.30)":"rgba(255,255,255,.30)");sh.addColorStop(1,"rgba(0,0,0,0)");ctx.fillStyle=sh;ctx.fillRect(0,0,1080,500);text("LOKA!",45,80,52,350,ink);text(String(p.city).toUpperCase(),540,72,25,520,ink,"center");text(dateLabel(p.date),1030,72,23,450,ink,"right");text(s.label,540,205,68,760,ink,"center");wrap(p.editorial.subtitle,540,280,860,40,32,470,ink,"center",2);const xs=[145,310,470,630,790,950];p.hourly.slice(0,6).forEach((h,i)=>{text(String(h.hour).padStart(2,"0")+"h",xs[i],390,30,470,ink,"center");text(icon(h.condition),xs[i],485,68,400,ink,"center");text(String(h.temperatureC)+"°",xs[i],610,54,650,ink,"center")});ctx.save();ctx.fillStyle="rgba(255,255,255,.88)";rr(62,930,956,350,30);ctx.fill();ctx.restore();p.editorial.summaryLines.slice(0,3).forEach((l,i)=>wrap(l,120,1018+i*98,840,36,28,430,"#17212b","left",2));text("Ici, aujourd’hui.",540,1330,23,380,ink,"center");document.getElementById("debug").innerHTML="<strong>"+String(s.id).padStart(2,"0")+" "+s.label+"</strong> · score "+s.score+" · "+s.confidence+"<br>Master : "+s.masterFileName+"<br>Editorial : "+p.editorial.source+"<br><strong>Produit effectif : V24</strong>"}
function file(){const b=atob(canvas.toDataURL("image/png").split(",")[1]),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return new File([u],"loka-"+p.date+".png",{type:"image/png"})}
function fallback(f){const u=URL.createObjectURL(f),a=document.createElement("a");a.href=u;a.download=f.name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),30000)}
document.getElementById("share").onclick=()=>{const f=file();if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[f]}))){navigator.share({files:[f],title:"LOKA!"}).catch(e=>{if(e?.name!=="AbortError")fallback(f)});return}fallback(f)};draw().catch(e=>document.getElementById("debug").textContent=String(e));
</script></body></html>`;
}
