import type { V24PublicPayloadPreview } from "../engine/publicPreview";
function esc(v:unknown):string{return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c] as string))}
function fmt(date:string,tz:string):string{try{return new Intl.DateTimeFormat("fr-FR",{timeZone:tz,weekday:"long",day:"numeric",month:"long"}).format(new Date(date+"T12:00:00"))}catch{return date}}
function glyph(c:string):string{c=String(c||"").toLowerCase();if(c.includes("orage"))return"ϟ";if(c.includes("pluie")||c.includes("averse"))return"☂︎";if(c.includes("soleil"))return"☀︎";if(c.includes("vent"))return"≋";if(c.includes("couvert"))return"●";return"◐"}
export function renderV24PrepublicationDashboard(p:V24PublicPayloadPreview,timezone:string):string{
 const hours=p.hourly.slice(0,6);
 return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive"><title>LOKA! — Prépublication V24</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f1ed;color:#22272d;font-family:-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;padding:18px 14px 28px}.shell{width:min(100%,580px);margin:auto;min-height:calc(100vh - 46px);display:flex;flex-direction:column}.badge{align-self:flex-start;background:#fff1cc;color:#76530a;border-radius:999px;padding:7px 11px;font-size:11px;font-weight:750}.top{display:flex;justify-content:space-between;margin-top:18px}.brand{font-size:12px;letter-spacing:.16em;color:#777}.engine{text-align:right;font-size:10px;color:#999}.intro{text-align:center;padding-top:34px}.city{font-size:17px;letter-spacing:.24em}.date{font-size:13px;color:#777;margin-top:8px}.scene{text-align:center;padding:26px 0 20px}.scene small{color:#999;letter-spacing:.12em}.scene h1{font-size:clamp(32px,8vw,46px);margin:8px 0}.hero{position:relative;border-radius:30px;overflow:hidden;height:310px;background:#ddd}.hero img{width:100%;height:100%;object-fit:cover}.shade{position:absolute;inset:0;background:linear-gradient(to bottom,rgba(0,0,0,.05),rgba(0,0,0,.48))}.verdict{position:absolute;left:22px;right:22px;bottom:22px;color:white;font-size:24px;font-weight:650}.temps{text-align:center;padding:25px 0}.max{font-size:84px;line-height:.9;font-weight:320}.min{font-size:12px;color:#999;margin-top:12px}.hours{display:grid;grid-template-columns:repeat(6,1fr);background:rgba(255,255,255,.82);padding:20px 8px;border-radius:28px}.hour{text-align:center;display:grid;gap:8px}.hour span{font-size:10px;color:#92969a}.icon{font-size:21px;color:#d3a74b}.hour strong{font-size:16px;font-weight:500}.summary{margin-top:15px;background:rgba(255,255,255,.62);border-radius:24px;padding:18px 21px}.title{text-transform:uppercase;letter-spacing:.14em;color:#aaa;font-size:9px}.line{font-size:17px;line-height:1.35;padding:9px 0;border-top:1px solid rgba(0,0,0,.06)}.line:first-of-type{margin-top:5px;border-top:0}.meta{margin-top:14px;background:#fff;border-radius:20px;padding:15px;font-size:11px;color:#777;line-height:1.55}.actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.actions a{padding:14px;text-align:center;text-decoration:none;background:#ecece8;color:#171715;border-radius:15px;font-size:13px;font-weight:650}footer{margin-top:auto;padding-top:28px;text-align:center;color:#aaa;font-family:Georgia,serif;font-style:italic}
</style></head><body><main class="shell"><div class="badge">V24 PREPUBLICATION — NON PUBLIÉ</div><div class="top"><div class="brand">LOKA!</div><div class="engine">MOTEUR OFFICIEL<br><strong>LEGACY</strong></div></div><section class="intro"><div class="city">${esc(p.city.toUpperCase())}</div><div class="date">${esc(fmt(p.date,timezone))}</div></section><section class="scene"><small>${String(p.scene.id).padStart(2,"0")} · ${esc(p.scene.key)}</small><h1>${esc(p.scene.label)}</h1><small>${esc(p.scene.family)}</small></section><section class="hero"><img src="${esc(p.scene.masterUrl)}"><div class="shade"></div><div class="verdict">${esc(p.editorial.mainVerdict)}</div></section><section class="temps"><div class="max">${p.temperatures.maxC}°</div><div class="min">minimum ${p.temperatures.minC}°</div></section><section class="hours">${hours.map(h=>`<div class="hour"><span>${h.hour}h</span><div class="icon">${glyph(h.condition)}</div><strong>${h.temperatureC}°</strong></div>`).join("")}</section><section class="summary"><div class="title">Aujourd’hui — V24</div>${p.editorial.summaryLines.map(l=>`<div class="line">${esc(l)}</div>`).join("")}</section>${p.editorial.notableEvent?`<section class="summary"><div class="title">À noter</div><div class="line">${esc(p.editorial.notableEvent)}</div></section>`:""}<div class="meta"><strong>Prépublication uniquement.</strong><br>Master ${esc(p.scene.masterFileName)} · score ${p.scene.score} · confiance ${esc(p.scene.confidence)}.<br>forecast.scene officiel reste ${esc(p.legacyCompatibility.forecastScene??"—")}.</div><div class="actions"><a href="/instagram24-preview">Studio Instagram V24</a><a href="/admin">Retour Admin</a></div><footer>Ici, aujourd’hui.</footer></main></body></html>`;
}
