-- Daily Insight editorial selections generated by the isolated laboratory.
-- The active Daily publication pipeline never reads this table.
CREATE TABLE IF NOT EXISTS daily_insight_editorial_drafts (
  city_slug TEXT NOT NULL,
  target_date TEXT NOT NULL,
  engine_version TEXT NOT NULL,
  bundle_id TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('SELECTED', 'NO_ELIGIBLE_CANDIDATE', 'DATA_NOT_READY')),
  winner_detector_id TEXT,
  winner_family TEXT,
  winner_score INTEGER,
  generated_at TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (city_slug, target_date)
);

CREATE INDEX IF NOT EXISTS idx_daily_insight_editorial_drafts_generated
ON daily_insight_editorial_drafts(city_slug, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_daily_insight_editorial_drafts_winner
ON daily_insight_editorial_drafts(city_slug, winner_detector_id, target_date DESC);
